/* Evia7 photo tips: one short line for each "thing to capture", telling the learner what the photo should show.
   window.eviaPhotoTip(item) returns the tip, or a general one for anything not listed. */
(function(){
  const T={
    "adhesive":"The adhesive tub or tube label, and it being applied.",
    "adhesives":"The adhesive labels, and them being applied.",
    "architrave":"The fitted architrave, close up on the mitres at the head.",
    "balustrades":"The whole balustrade, then close up on a spindle joint.",
    "biscuit":"The biscuit slots cut, then the joint glued and clamped.",
    "brick repairs":"The damaged bricks before, then the finished repair.",
    "bridal":"The bridle joint cut, then fitted together.",
    "capping":"The capping along the top of the wall, with its overhang.",
    "casement":"The casement fitted in the frame, open and closed.",
    "cavity closure":"The cavity closer fitted at the reveal, before the frame goes in.",
    "cavity setting-out":"Both leaves set out, with the tape showing the cavity width.",
    "cavity trays":"The tray over the opening, with stop ends and weep holes.",
    "cladding":"The battens on the membrane, then the boards fixed.",
    "communication":"You talking through the job with your supervisor or team.",
    "construction":"The wall going up, with your line and pins in shot.",
    "coverings":"The floor or roof covering laid, close up on a joint.",
    "cutting":"You cutting safely, with guards and PPE in shot.",
    "cutting list":"Your cutting list next to the timber it’s for.",
    "damaged bricks":"The damaged bricks close up, before you start.",
    "door frames":"The frame fixed in the opening, with a level on the jamb.",
    "doors":"The hung door, closed, showing even gaps round it.",
    "dovetail":"The tails and pins marked, then the joint fitted.",
    "dowels":"The dowel holes drilled, then the joint glued up.",
    "dpcs":"The DPC laid on the mortar bed, with its lap showing.",
    "drawings":"The drawing you worked from, with the part you built.",
    "drawings/specifications":"The drawing or spec you worked from, next to the job.",
    "eaves":"The eaves detail: fascia, soffit and ventilation.",
    "edge sill":"The sill bedded, with its fall and overhang showing.",
    "environmental practices":"Waste sorted into the right skips or bags.",
    "fire stopping":"The fire stopping fitted round the service, with its label.",
    "fixed machinery":"The machine set up, with its guard in place.",
    "floor joists":"The joists at their centres, with the tape in shot.",
    "flush":"The flush joint finish close up.",
    "gable/garden wall":"The whole wall, then close up on the bond.",
    "gauge rods":"Your gauge rod marked up, held against the work.",
    "gauging":"Your gauging buckets or boxes, struck off level.",
    "glazing rebates":"The rebates cut clean, ready for the glass.",
    "half round":"The half round (bucket handle) joint finish close up.",
    "halving":"The halving joint cut, then fitted together.",
    "hand tools":"The tools you used, laid out clean.",
    "hand/mechanical":"The mix being made, by hand or in the mixer.",
    "handrails":"The handrail fixed, with its height measured.",
    "hinging":"The hinges let in flush, with the screws in.",
    "insulation":"The insulation fitted tight, with no gaps.",
    "ironmongery":"The handle, lock or hinges fitted, close up.",
    "jigs":"Your jig set up, then the part it made.",
    "joint finishes":"The finished joints close up, all the same style.",
    "joints":"The joint cut, then fitted together.",
    "laser level":"The laser set up, with its line on the work.",
    "levels":"The level on the work, with the bubble in shot.",
    "linings":"The lining fixed in the opening, with a level on it.",
    "lintel":"The lintel bedded, with its bearing at each end.",
    "load-bearing studwork":"The studwork frame, with the head and sole plates.",
    "loft access":"The loft hatch framed out and finished.",
    "marking out":"Your marks on the work, with the square or tape.",
    "material estimation":"Your working out, next to the materials.",
    "measuring":"The tape on the work, with the reading in shot.",
    "measuring/marking":"Your measurements and marks on the work.",
    "mitring":"The mitre cut, then the joint closed up tight.",
    "mixing mortar":"The mix being made, then the finished mortar.",
    "mortar quantity":"How much mortar you mixed for the job.",
    "mortise/tenon":"The mortise and tenon cut, then the joint fitted.",
    "nails/screws/bolts":"The fixings you chose, and them used in the work.",
    "openings":"The opening built, with its reveals plumb.",
    "power tools":"The power tool with its guard, and you using it safely.",
    "ppe":"You wearing your PPE: hat, hi-vis, boots, gloves and glasses.",
    "pre-mix":"The pre-mix tub, with its label and use-by time.",
    "profiles":"The profile boards set up, with the lines on.",
    "protection":"The new work covered and protected.",
    "rafter roofs":"The rafters fixed at the ridge and the wall plate.",
    "raking cut":"The raking cut, with the bevel on the angle.",
    "ratio":"Your gauging for the mix ratio, like 1 cement to 4 sand.",
    "recessed":"The recessed joint finish close up.",
    "recessing":"The recess cut clean, ready for the fitting.",
    "returns":"The corner return, with the bond turning the corner.",
    "safe working":"Your work area: tidy, safe and signed.",
    "safe working area":"Your work area set up safely before you start.",
    "safety":"The safety measures in place around your work.",
    "safety equipment":"The safety kit in place, like guards or edge protection.",
    "safety signage":"The safety signs at your work area.",
    "scribing":"The scribed piece fitting tight to the uneven surface.",
    "service encasement":"The boxing round the pipes, with an access panel.",
    "silos":"The silo you used, with the mixer and the water feed.",
    "skirting":"The skirting fixed, close up on a corner joint.",
    "soldiers":"The soldier course, with the bricks upright and plumb.",
    "solid wall construction":"The solid wall, then close up on the bond.",
    "specifications":"The spec you worked to, next to the job.",
    "spindles":"The spindles fixed evenly, with a gap check.",
    "splicing":"The splice joint, glued and fixed.",
    "squares":"Your square on the corner, showing it’s true.",
    "staples":"The staples fixing the membrane or insulation.",
    "straight staircase":"The whole flight, then close up on a tread and riser.",
    "straight stairs":"The whole flight, then close up on a tread and riser.",
    "stretcher bond":"The wall in stretcher bond, with the half-bond lap showing.",
    "structural carcassing":"The joists or rafters fixed, with the hangers or fixings.",
    "structural fixings":"The hangers, straps or bolts, fitted close up.",
    "teamwork":"You working with the team on the job.",
    "timber doors":"The door made up, then close up on a joint.",
    "timber mouldings":"The moulding profile close up.",
    "timber sizing":"The timber with the tape showing its size.",
    "timber window":"The window made or fitted, then close up on a joint.",
    "timber/metal partitions":"The partition frame, with the studs at their centres.",
    "tool maintenance":"Your tools cleaned, sharpened or checked.",
    "trussed/traditional roofs":"The roof timbers fixed, with the bracing.",
    "verge":"The verge detail finished along the gable.",
    "wall setting-out":"Your setting-out lines, with the tape or square in shot.",
    "wall ties":"The ties in the bed joint, drip down, at the right spacing.",
    "wall/floor units":"The units fixed level, with the level on top.",
    "weather struck":"The weather struck joint finish close up.",
    "weep holes":"The weep holes above the tray or lintel.",
    "window boards":"The window board fitted, with its horns and nosing.",
    /* Trowel Occupations L3 */
    "you wearing your ppe":"You wearing your PPE: hat, hi-vis, boots, gloves and glasses.",
    "turning piece or centre":"The turning piece or centre in place, before the arch goes on.",
    "springing points":"The springing points marked, level both sides.",
    "voussoirs":"The voussoirs close up, with even joints radiating from the centre.",
    "key brick":"The key brick in the centre of the arch.",
    "flue liners":"The flue liners jointed, with the sockets facing up.",
    "oversailing courses":"The oversailing courses projecting at the top of the stack.",
    "movement joints":"The movement joint, clear of mortar, with filler and sealant.",
    "wind posts or restraints":"The wind posts or restraints fixed, top and bottom.",
    "wind post positions":"Where the wind posts go, marked out.",
    "support angles":"The support angle bolted on, level, before the bricks go on.",
    "support angle fixings":"The bolts and shims on the support angle, close up.",
    "special bricks":"The special bricks (like bullnose or plinth) in place.",
    "fire bricks and throat":"The fire bricks and the throat above the opening.",
    "propping (needles and props)":"The needles and props in place before any cutting out.",
    "thin joint blocks":"The thin joint blocks laid, with the thin mortar bed.",
    "mixing jointing compound":"The jointing mortar being mixed to the maker’s instructions.",
    "trammel or template":"Your trammel or template in use on the curve.",
    "template or rod":"Your template or rod held against the work.",
    "centre point and radius":"The centre point and the radius rod or line from it.",
    "the damage":"The damage close up, before you start the repair.",
    "the existing wall":"The existing wall before you start, with any damage.",
    "matching bricks and mortar":"The new bricks and mortar next to the old, to show they match.",
    "making good":"The area made good around the new work.",
    "tank or treatment plant":"The tank or treatment plant set level on its base.",
    "cover and frame":"The cover and frame bedded level with the ground.",
    "access equipment":"The scaffold or platform you worked from, with its tag.",
    "testing":"The test being done, with the result showing.",
    "joint finish":"The joint finish close up, all the same style.",
    "straight runs":"The straight run of wall, lined through.",
    "gauge rod":"Your gauge rod marked up, held against the work.",
    "both leaves":"Both leaves going up together, with the cavity clear.",
    "returns or piers":"The return or pier, with the bond tied in.",
    "closers":"The closers in place at the quoin or reveal.",
    "soffit system components":"The soffit parts laid out, then fixed in place.",
    "bricks or slips fitted":"The bricks or slips fixed, close up on the joints.",
    "new work in":"The new work built in, matching the old.",
    "connections":"The connections made, before they’re covered."
  };
  /* Anything not listed gets a tip from the kind of thing it is. */
  const RULES=[
    [/^finished\b/,x=>"The "+x+": one wide shot, then close up on the detail."],
    [/setting out|lines and pegs|corner pegs|profiles|datum|reveal lines|positions?\b/,()=>"Your setting-out marks and lines, with the tape or square in shot."],
    [/check|angle checks|square/,()=>"You checking it, with the tool and the reading in shot."],
    [/\bties?\b|fixings|channels?\b|reinforcement|toothing/,()=>"The ties or fixings in place, close up, at their spacing."],
    [/bond/,()=>"The bond close up, showing the laps."],
    [/cut/,()=>"The cuts close up, neat and accurate, cut safely with PPE."],
    [/dpc|tray|flashing|barrier|seals?\b|membrane|laps/,()=>"It fitted in place, close up on the laps and stop ends."],
    [/pipe|gull|benching|chamber|trench|backfill|inlet|outlet|soakaway|fall/,()=>"The pipework and falls, before it’s covered up."],
    [/lintel|arch|opening|reveal/,()=>"The opening with its lintel or arch, and the bearings."],
    [/level|base course/,()=>"The level on the work, with the bubble in shot."],
    [/coping|capping|cill/,()=>"The top of the wall finished, with the drip and overhang."],
    [/curve|radius|splay|angle/,()=>"The shape of it, with your template or rod against it."],
    [/feature|corbel|plinth|string|dentil|panel|decorative/,()=>"The feature course close up, lined through and level."]
  ];
  window.eviaPhotoTip=item=>{
    const x=String(item||"").trim().toLowerCase();if(T[x])return T[x];
    const r=RULES.find(([re])=>re.test(x));return r?r[1](x):"One photo of the whole thing, then one close up.";
  };
})();
