/* Evia7 college practice tasks. Each task names the confidence-check skills it practises (the names must match
   confidenceQuestions() in app.js). Evia picks the tasks that cover the most skills a learner rated low. */
window.EVIA_PRACTICE_TASKS={
  bricklayer:[
    {id:"cavity-opening",title:"Cavity wall panel with a window opening",time:"2–3 workshop sessions",
     skills:["Cavity wall setting out","Cavity wall construction","Lintels","Materials","Cutting bricks","Jointing styles","Joint protection"],
     brief:"Build a short stretcher-bond cavity wall with a return and a window opening, from a drawing.",
     steps:["Set out from the drawing: check dimensions, mark the opening and set up a gauge rod","Build both leaves to DPC level and lay the DPC","Place wall ties at the spacing on the drawing, with insulation if specified","Form the opening: cavity closers, cavity tray and weep holes","Bed the lintel with the correct bearing at each end, then continue the courses over","Finish the joints and cover the work at the end of each session"],
     check:"Ask your tutor to check gauge, plumb, level, tie spacing and lintel bearing before you take it down."},
    {id:"bonds-return",title:"One-brick wall in English and Flemish bond",time:"1–2 workshop sessions",
     skills:["Setting out a solid wall","Brick bonds","Mortar mixing","Jointing styles","Cutting bricks"],
     brief:"Build two short one-brick walls with a return corner: one in English bond, one in Flemish bond.",
     steps:["Mix your own mortar to the ratio your tutor gives you","Dry-bond the first course to work out the closers and cuts","Set out the corner square using the 3-4-5 method","Build the corners first, then run in to the line","Cut your closers accurately with a bolster and club hammer","Finish half the wall flush and half with a weather-struck or bucket-handle joint"],
     check:"Ask your tutor to check the bond pattern, perpends, the corner's square and your joint finish."},
    {id:"gable",title:"Raking gable end panel",time:"2 workshop sessions",
     skills:["Raking cuts","Cutting bricks","Setting out a solid wall","Jointing styles"],
     brief:"Build a small gable end with raking cuts to a set pitch.",
     steps:["Set out the wall and mark the pitch with a rake line or profile","Build the main courses to the springing point","Measure and mark each raking cut from the line","Cut the bricks cleanly and lay them to the rake","Point up and check the rake is straight"],
     check:"Ask your tutor to check the pitch, the neatness of your cuts and that the rake line is true."},
    {id:"garden-repair",title:"Garden wall with a pier, plus a repair",time:"2 workshop sessions",
     skills:["Brick bonds","Brick repairs","Mortar mixing","Materials","Joint protection"],
     brief:"Build a garden wall bond panel with a pier, then cut out and replace one brick.",
     steps:["Choose suitable bricks and mortar for an exposed garden wall","Build the panel in English or Flemish garden wall bond with a pier","Protect it from rain or frost while it cures","In a later session, rake out and cut out one brick without damaging the others","Bed the replacement brick and match the joint finish"],
     check:"Ask your tutor to check the bond, the pier and how neat the repair is."},
    {id:"joint-sampler",title:"Mortar and joint finish sample board",time:"1 workshop session",
     skills:["Mortar mixing","Jointing styles","Joint protection"],
     brief:"Build a small sample panel showing four different joint finishes.",
     steps:["Gauge and mix mortar to a set ratio, keeping it consistent between batches","Build a small panel, about 4 courses high","Finish each quarter differently: flush, recessed, half-round (bucket handle) and weather-struck","Explain when each finish is used","Cover the panel to protect it"],
     check:"Ask your tutor to check each finish and your mortar consistency."}
  ],
  site:[
    {id:"stud-door",title:"Stud partition with a door opening",time:"2–3 workshop sessions",
     skills:["Partition walls","Structural carcassing","Doors","Skirting and architrave"],
     brief:"Build a timber stud partition with a door opening, then line it, hang the door and fit the trim.",
     steps:["Set out the head and sole plates from the drawing","Fix the studs and noggins at the spacing given","Form the door opening with the right trimmers","Fit the door lining plumb and square","Hang the door and fit hinges and latch","Fit the architrave and skirting with neat mitres"],
     check:"Ask your tutor to check plumb, stud spacing, the door gaps and your mitres."},
    {id:"joist-floor",title:"Floor joist section with a trimmed opening",time:"2 workshop sessions",
     skills:["Floor joists","Structural carcassing","Service encasement"],
     brief:"Set out a small floor with joist hangers, a trimmed opening and a boarded finish.",
     steps:["Set out the joist centres from the drawing","Fix the joist hangers and joists, keeping the tops level","Trim an opening with trimmer and trimming joists","Fit strutting or noggins","Board the floor, leaving a removable access panel for services"],
     check:"Ask your tutor to check joist centres, level and the trimming details."},
    {id:"stair-mockup",title:"Stair installation mock-up",time:"2 workshop sessions",
     skills:["Stairs","Handrails and spindles"],
     brief:"Install a short straight flight in the workshop rig, then fit the handrail and spindles.",
     steps:["Check the rise and going against the drawing","Position and fix the strings level and secure","Fit the newel posts plumb","Cut and fit the handrail at the right height","Space the spindles evenly within the allowed gap"],
     check:"Ask your tutor to check handrail height, spindle gaps and that the flight is secure."},
    {id:"second-fix",title:"Second-fix room corner",time:"1–2 workshop sessions",
     skills:["Skirting and architrave","Window boards","Service encasement","Units and fitments"],
     brief:"Second-fix a room corner in the workshop: window board, boxing-in, skirting and a small unit.",
     steps:["Measure, mark and cut the window board, scribing it to the wall","Box in a pipe run with a removable panel","Fit the skirting with a scribed internal corner and a mitred external corner","Fit a small wall or base unit level and secure"],
     check:"Ask your tutor to check your scribes, mitres and that everything is level and secure."},
    {id:"roof-cladding",title:"Cut roof section with cladding panel",time:"2–3 workshop sessions",
     skills:["Roofs","Cladding","Structural carcassing"],
     brief:"Build a small cut-roof section with eaves and verge details, plus a timber cladding panel.",
     steps:["Set out the rafters from the pitch and span","Cut the plumb and seat cuts, then fix the rafters to the wall plate","Form the eaves and verge details","Fix battens and timber cladding boards to a test panel","Check fixings, spacing and ventilation gaps"],
     check:"Ask your tutor to check your cuts, rafter spacing and the eaves and verge details."}
  ],
  joiner:[
    {id:"joint-board",title:"Woodworking joint sampler board",time:"2 workshop sessions",
     skills:["Woodworking joints","Power tools","Drawings","Materials"],
     brief:"Make a sampler board with a mortise and tenon, a bridle, a halving and a dovetail joint.",
     steps:["Draw a simple cutting list from the drawing","Select and check your timber for defects","Mark out each joint accurately with a gauge and square","Cut the joints by hand, and with power tools you’re signed off on","Dry-fit, adjust, then glue and clamp"],
     check:"Ask your tutor to check the fit of each joint and how accurate your marking out is."},
    {id:"casement",title:"Casement window from a setting-out rod",time:"3–4 workshop sessions",
     skills:["Timber windows","Drawings","Fixed machinery","Ironmongery","Materials"],
     brief:"Set out a rod and make a small casement window with a glazing rebate and ironmongery.",
     steps:["Produce a setting-out rod from the drawing","Prepare a cutting list and select the timber","Machine the sections, only on machines you’re trained and signed off on, with your tutor’s permission","Cut the joints and assemble the frame and casement","Fit the hinges and fastener, and check the gaps"],
     check:"Ask your tutor to check your rod, the joints and how the casement opens and closes."},
    {id:"door-frame",title:"Door frame and door",time:"3 workshop sessions",
     skills:["Door frames and linings","Timber doors","Ironmongery","Woodworking joints"],
     brief:"Make a door frame, then a small framed door to fit it, and hang it.",
     steps:["Mark out and cut the frame joints","Assemble the frame square and check the diagonals","Make the door with the joints your tutor specifies","Hang the door with even gaps","Fit the hinges, a lock or latch and the keep"],
     check:"Ask your tutor to check square, the gaps round the door and the ironmongery."},
    {id:"mini-stair",title:"Three-step staircase with spindles",time:"3–4 workshop sessions",
     skills:["Straight staircases","Staircase spindles","Drawings","Fixed machinery"],
     brief:"Set out and make a short flight of stairs, then fit spindles to a handrail.",
     steps:["Work out the rise and going from the drawing","Set out and cut the housings in the strings","Make and fit the treads and risers, wedged and glued","Fit the newel and handrail","Cut and fit the spindles evenly spaced"],
     check:"Ask your tutor to check the rise and going, the housings and the spindle spacing."},
    {id:"unit",title:"Wall unit carcass",time:"2 workshop sessions",
     skills:["Wall and floor units","Power tools","Materials","Ironmongery"],
     brief:"Make a small wall unit carcass with a shelf and a hung door.",
     steps:["Choose sheet materials and work out a cutting list","Cut the panels to size","Join the carcass and fit the back square","Fit an adjustable shelf","Hang the door on concealed hinges and adjust it"],
     check:"Ask your tutor to check square, the joints and the door alignment."}
  ],
  trowel3:[
    {id:"l3-arch",title:"Segmental arch over an opening",time:"2–3 workshop sessions",
     skills:["Arches","Setting out","Drawings and information","Decorative work"],
     brief:"Set out and build a segmental arch in brick over a small opening, using a turning piece.",
     steps:["Read the drawing and work out the span, rise and springing line","Set out the arch full size on a board: centre point, radius and voussoir positions","Set up the turning piece at the springing line and check it's level","Lay the voussoirs from each side, keeping joints radial and the same thickness","Set the key brick, point the joints, then ease and strike the turning piece once the mortar has gone off"],
     check:"Ask your tutor to check your setting out, the radial joints and the rise before the turning piece comes out."},
    {id:"l3-curve",title:"Wall curved on plan, with a splayed return",time:"2 workshop sessions",
     skills:["Curved and splayed walls","Setting out","Masonry structures","Drawings and information"],
     brief:"Build a short half-brick wall curved on plan, finishing with a splayed return at one end.",
     steps:["Set out the radius with a trammel and mark the curve on the base","Make a template from the radius to check the curve as you go","Build the curve, keeping perpends even and checking with the template every course","Set out the splay angle and cut or use squints at the return","Finish the joints and check plumb, level and the curve"],
     check:"Ask your tutor to check the curve against your template, the splay angle and your cuts."},
    {id:"l3-setting-out",title:"Set out a small building from drawings",time:"1–2 workshop sessions",
     skills:["Setting out","Drawings and information","Planning work","Methods of work"],
     brief:"Set out the corners, openings and levels of a small building from a drawing, using profiles and lines.",
     steps:["Read the drawing and list the dimensions and levels you need","Establish a datum and transfer it to your profiles","Set out the main lines and check square with 3-4-5 and the diagonals","Mark door and window openings on the lines","Write a short method statement for how you'd build it"],
     check:"Ask your tutor to check your diagonals, the datum and the opening positions before you strike the lines."},
    {id:"l3-repair",title:"Cut out and repair damaged brickwork",time:"1–2 workshop sessions",
     skills:["Repairs","Masonry structures","Methods of work","Working relationships"],
     brief:"Cut out a section of damaged brickwork and replace it, matching the bricks, bond and joint.",
     steps:["Identify the cause of the damage and plan the repair with your tutor","Set up a safe area and agree what needs propping, if anything","Cut out the damaged bricks without disturbing the ones around them","Match the new bricks, mortar colour and joint finish to the existing wall","Tooth in the new work, point up and clean down"],
     check:"Ask your tutor to check how well the repair matches, the bond and how cleanly you cut out."},
    {id:"l3-chimney",title:"Corbelled feature or chimney stack section",time:"2–3 workshop sessions",
     skills:["Chimneys and fireplaces","Decorative work","Masonry cladding","Drawings and information"],
     brief:"Build a short chimney stack section, or a decorative panel with corbelled and projecting courses.",
     steps:["Read the drawing and set out the stack or panel","Build the core, keeping the flue or panel square and plumb","Form the corbel or projecting courses, keeping projections even","Show where DPCs, trays or flashings would go","Finish the joints and clean down"],
     check:"Ask your tutor to check the projections, plumb and how you've shown the weathering details."}
  ]
};
