/* Evia7 college practice tasks. Each task names the confidence-check skills it practises (the names must match
   confidenceQuestions() in app.js). Evia picks the tasks that cover the most skills a learner rated low. */
window.EVIA_PRACTICE_TASKS={
  bricklayer:[
    {id:"cavity-opening",title:"Cavity wall panel with a window opening",time:"2–3 workshop sessions",
     skills:["Cavity wall setting out","Cavity wall construction","Lintels","Materials","Cutting bricks","Jointing styles","Joint protection"],
     brief:"Build a short stretcher-bond cavity wall with a return and a window opening, from a drawing.",
     steps:["Set out from the drawing: check dimensions, mark the opening and set up a gauge rod","Build both leaves to DPC level and lay the DPC","Place wall ties at the spacing on the drawing, with insulation if specified","Form the opening: cavity closers, cavity tray and weep holes","Bed the lintel with the correct bearing at each end, then continue the courses over","Finish the joints and cover the work at the end of each session"],
     check:"Ask your tutor to check gauge, plumb, level, tie spacing and lintel bearing before you take it down."},
    {id:"bonds-return",title:"One-brick wall in English and Flemish bond",time:"1–2 workshop sessions",
     skills:["Setting out a solid wall","Brick bonds","Mortar mixing","Jointing styles","Cutting bricks"],
     brief:"Build two short one-brick walls with a return corner: one in English bond, one in Flemish bond.",
     steps:["Mix your own mortar to the ratio your tutor gives you","Dry-bond the first course to work out the closers and cuts","Set out the corner square using the 3-4-5 method","Build the corners first, then run in to the line","Cut your closers accurately with a bolster and club hammer","Finish half the wall flush and half with a weather-struck or bucket-handle joint"],
     check:"Ask your tutor to check the bond pattern, perpends, the corner's square and your joint finish."},
    {id:"gable",title:"Raking gable end panel",time:"2 workshop sessions",
     skills:["Raking cuts","Cutting bricks","Setting out a solid wall","Jointing styles"],
     brief:"Build a small gable end with raking cuts to a set pitch.",
     steps:["Set out the wall and mark the pitch with a rake line or profile","Build the main courses to the springing point","Measure and mark each raking cut from the line","Cut the bricks cleanly and lay them to the rake","Point up and check the rake is straight"],
     check:"Ask your tutor to check the pitch, the neatness of your cuts and that the rake line is true."},
    {id:"garden-repair",title:"Garden wall with a pier, plus a repair",time:"2 workshop sessions",
     skills:["Brick bonds","Brick repairs","Mortar mixing","Materials","Joint protection"],
     brief:"Build a garden wall bond panel with a pier, then cut out and replace one brick.",
     steps:["Choose suitable bricks and mortar for an exposed garden wall","Build the panel in English or Flemish garden wall bond with a pier","Protect it from rain or frost while it cures","In a later session, rake out and cut out one brick without damaging the others","Bed the replacement brick and match the joint finish"],
     check:"Ask your tutor to check the bond, the pier and how neat the repair is."},
    {id:"joint-sampler",title:"Mortar and joint finish sample board",time:"1 workshop session",
     skills:["Mortar mixing","Jointing styles","Joint protection"],
     brief:"Build a small sample panel showing four different joint finishes.",
     steps:["Gauge and mix mortar to a set ratio, keeping it consistent between batches","Build a small panel, about 4 courses high","Finish each quarter differently: flush, recessed, half-round (bucket handle) and weather-struck","Explain when each finish is used","Cover the panel to protect it"],
     check:"Ask your tutor to check each finish and your mortar consistency."}
  ],
  site:[
    {id:"stud-door",title:"Stud partition with a door opening",time:"2–3 workshop sessions",
     skills:["Partition walls","Structural carcassing","Doors","Skirting and architrave"],
     brief:"Build a timber stud partition with a door opening, then line it, hang the door and fit the trim.",
     steps:["Set out the head and sole plates from the drawing","Fix the studs and noggins at the spacing given","Form the door opening with the right trimmers","Fit the door lining plumb and square","Hang the door and fit hinges and latch","Fit the architrave and skirting with neat mitres"],
     check:"Ask your tutor to check plumb, stud spacing, the door gaps and your mitres."},
    {id:"joist-floor",title:"Floor joist section with a trimmed opening",time:"2 workshop sessions",
     skills:["Floor joists","Structural carcassing","Service encasement"],
     brief:"Set out a small floor with joist hangers, a trimmed opening and a boarded finish.",
     steps:["Set out the joist centres from the drawing","Fix the joist hangers and joists, keeping the tops level","Trim an opening with trimmer and trimming joists","Fit strutting or noggins","Board the floor, leaving a removable access panel for services"],
     check:"Ask your tutor to check joist centres, level and the trimming details."},
    {id:"stair-mockup",title:"Stair installation mock-up",time:"2 workshop sessions",
     skills:["Stairs","Handrails and spindles"],
     brief:"Install a short straight flight in the workshop rig, then fit the handrail and spindles.",
     steps:["Check the rise and going against the drawing","Position and fix the strings level and secure","Fit the newel posts plumb","Cut and fit the handrail at the right height","Space the spindles evenly within the allowed gap"],
     check:"Ask your tutor to check handrail height, spindle gaps and that the flight is secure."},
    {id:"second-fix",title:"Second-fix room corner",time:"1–2 workshop sessions",
     skills:["Skirting and architrave","Window boards","Service encasement","Units and fitments"],
     brief:"Second-fix a room corner in the workshop: window board, boxing-in, skirting and a small unit.",
     steps:["Measure, mark and cut the window board, scribing it to the wall","Box in a pipe run with a removable panel","Fit the skirting with a scribed internal corner and a mitred external corner","Fit a small wall or base unit level and secure"],
     check:"Ask your tutor to check your scribes, mitres and that everything is level and secure."},
    {id:"roof-cladding",title:"Cut roof section with cladding panel",time:"2–3 workshop sessions",
     skills:["Roofs","Cladding","Structural carcassing"],
     brief:"Build a small cut-roof section with eaves and verge details, plus a timber cladding panel.",
     steps:["Set out the rafters from the pitch and span","Cut the plumb and seat cuts, then fix the rafters to the wall plate","Form the eaves and verge details","Fix battens and timber cladding boards to a test panel","Check fixings, spacing and ventilation gaps"],
     check:"Ask your tutor to check your cuts, rafter spacing and the eaves and verge details."}
  ],
  joiner:[
    {id:"joint-board",title:"Woodworking joint sampler board",time:"2 workshop sessions",
     skills:["Woodworking joints","Power tools","Drawings","Materials"],
     brief:"Make a sampler board with a mortise and tenon, a bridle, a halving and a dovetail joint.",
     steps:["Draw a simple cutting list from the drawing","Select and check your timber for defects","Mark out each joint accurately with a gauge and square","Cut the joints by hand, and with power tools you’re signed off on","Dry-fit, adjust, then glue and clamp"],
     check:"Ask your tutor to check the fit of each joint and how accurate your marking out is."},
    {id:"casement",title:"Casement window from a setting-out rod",time:"3–4 workshop sessions",
     skills:["Timber windows","Drawings","Fixed machinery","Ironmongery","Materials"],
     brief:"Set out a rod and make a small casement window with a glazing rebate and ironmongery.",
     steps:["Produce a setting-out rod from the drawing","Prepare a cutting list and select the timber","Machine the sections, only on machines you’re trained and signed off on, with your tutor’s permission","Cut the joints and assemble the frame and casement","Fit the hinges and fastener, and check the gaps"],
     check:"Ask your tutor to check your rod, the joints and how the casement opens and closes."},
    {id:"door-frame",title:"Door frame and door",time:"3 workshop sessions",
     skills:["Door frames and linings","Timber doors","Ironmongery","Woodworking joints"],
     brief:"Make a door frame, then a small framed door to fit it, and hang it.",
     steps:["Mark out and cut the frame joints","Assemble the frame square and check the diagonals","Make the door with the joints your tutor specifies","Hang the door with even gaps","Fit the hinges, a lock or latch and the keep"],
     check:"Ask your tutor to check square, the gaps round the door and the ironmongery."},
    {id:"mini-stair",title:"Three-step staircase with spindles",time:"3–4 workshop sessions",
     skills:["Straight staircases","Staircase spindles","Drawings","Fixed machinery"],
     brief:"Set out and make a short flight of stairs, then fit spindles to a handrail.",
     steps:["Work out the rise and going from the drawing","Set out and cut the housings in the strings","Make and fit the treads and risers, wedged and glued","Fit the newel and handrail","Cut and fit the spindles evenly spaced"],
     check:"Ask your tutor to check the rise and going, the housings and the spindle spacing."},
    {id:"unit",title:"Wall unit carcass",time:"2 workshop sessions",
     skills:["Wall and floor units","Power tools","Materials","Ironmongery"],
     brief:"Make a small wall unit carcass with a shelf and a hung door.",
     steps:["Choose sheet materials and work out a cutting list","Cut the panels to size","Join the carcass and fit the back square","Fit an adjustable shelf","Hang the door on concealed hinges and adjust it"],
     check:"Ask your tutor to check square, the joints and the door alignment."}
  ],
  trowel3:[
    {id:"l3-arch",title:"Segmental arch over an opening",time:"2–3 workshop sessions",
     skills:["Arches","Setting out","Drawings and information","Decorative work"],
     brief:"Set out and build a segmental arch in brick over a small opening, using a turning piece.",
     steps:["Read the drawing and work out the span, rise and springing line","Set out the arch full size on a board: centre point, radius and voussoir positions","Set up the turning piece at the springing line and check it's level","Lay the voussoirs from each side, keeping joints radial and the same thickness","Set the key brick, point the joints, then ease and strike the turning piece once the mortar has gone off"],
     check:"Ask your tutor to check your setting out, the radial joints and the rise before the turning piece comes out."},
    {id:"l3-curve",title:"Wall curved on plan, with a splayed return",time:"2 workshop sessions",
     skills:["Curved and splayed walls","Setting out","Masonry structures","Drawings and information"],
     brief:"Build a short half-brick wall curved on plan, finishing with a splayed return at one end.",
     steps:["Set out the radius with a trammel and mark the curve on the base","Make a template from the radius to check the curve as you go","Build the curve, keeping perpends even and checking with the template every course","Set out the splay angle and cut or use squints at the return","Finish the joints and check plumb, level and the curve"],
     check:"Ask your tutor to check the curve against your template, the splay angle and your cuts."},
    {id:"l3-setting-out",title:"Set out a small building from drawings",time:"1–2 workshop sessions",
     skills:["Setting out","Drawings and information","Planning work","Methods of work"],
     brief:"Set out the corners, openings and levels of a small building from a drawing, using profiles and lines.",
     steps:["Read the drawing and list the dimensions and levels you need","Establish a datum and transfer it to your profiles","Set out the main lines and check square with 3-4-5 and the diagonals","Mark door and window openings on the lines","Write a short method statement for how you'd build it"],
     check:"Ask your tutor to check your diagonals, the datum and the opening positions before you strike the lines."},
    {id:"l3-repair",title:"Cut out and repair damaged brickwork",time:"1–2 workshop sessions",
     skills:["Repairs","Masonry structures","Methods of work","Working relationships"],
     brief:"Cut out a section of damaged brickwork and replace it, matching the bricks, bond and joint.",
     steps:["Identify the cause of the damage and plan the repair with your tutor","Set up a safe area and agree what needs propping, if anything","Cut out the damaged bricks without disturbing the ones around them","Match the new bricks, mortar colour and joint finish to the existing wall","Tooth in the new work, point up and clean down"],
     check:"Ask your tutor to check how well the repair matches, the bond and how cleanly you cut out."},
    {id:"l3-chimney",title:"Corbelled feature or chimney stack section",time:"2–3 workshop sessions",
     skills:["Chimneys and fireplaces","Decorative work","Masonry cladding","Drawings and information"],
     brief:"Build a short chimney stack section, or a decorative panel with corbelled and projecting courses.",
     steps:["Read the drawing and set out the stack or panel","Build the core, keeping the flue or panel square and plumb","Form the corbel or projecting courses, keeping projections even","Show where DPCs, trays or flashings would go","Finish the joints and clean down"],
     check:"Ask your tutor to check the projections, plumb and how you've shown the weathering details."}
  ]
};

/* Skills (Teach me): every task in hours (1 to 6, all at college), with a self mark sheet: what the learner checks on
   their own work before showing their tutor. The tasks above get their hours and marks here, and each course gets
   more ideas below, so Evia can always find something aimed at a skill the learner rated low. */
(function(){
  const T=window.EVIA_PRACTICE_TASKS,SAFE=["Worked safely in full PPE","Left the work area clean and tidy"];
  const more={
    "cavity-opening":{hours:6,marks:["Gauge right: 75 mm a course, checked with the gauge rod","Both leaves level and plumb (within 3 mm)","Ties at the right spacing, sloping down to the outer leaf","Lintel level with at least 150 mm bearing each end","Cavity clean with no mortar on the ties","Opening the right size, reveals plumb"]},
    "bonds-return":{hours:5,marks:["English and Flemish bond correct, with no straight joints","Corner square (3-4-5)","Level, plumb and to gauge","Closers in the right places","Joints full and finished neatly"]},
    "gable":{hours:5,marks:["Pitch matches the drawing","Raking cuts clean and following the line","Main courses level, plumb and to gauge","Cuts sized so no piece is too small","Joints finished neatly"]},
    "garden-repair":{hours:4,title:"Garden wall with a pier",skills:["Brick bonds","Materials","Joint protection","Mortar mixing"],
      brief:"Build a garden wall panel with a pier in English or Flemish garden wall bond, then protect it.",
      steps:["Choose suitable bricks and mortar for an exposed garden wall","Set out the panel and the pier from the drawing","Build it in English or Flemish garden wall bond, keeping it to gauge","Bond the pier in properly on every course","Finish the joints and protect the wall from rain or frost"],
      check:"Ask your tutor to check the bond, the pier and how you've protected it.",
      marks:["Garden wall bond correct throughout","Pier bonded in on every course","Level, plumb and to gauge","Suitable bricks and mortar for an outside wall","Wall covered and protected properly"]},
    "joint-sampler":{hours:2,marks:["Mortar mixed to the ratio, same colour in every batch","Four finishes done: flush, recessed, half round, weather-struck","Each finish even along its length","Can explain where each finish is used","Face clean, no smears"]},
    "stud-door":{hours:6,marks:["Studs at the right centres from the drawing","Head and sole plates straight and fixed","Door opening the right size, lining plumb and square","Door gaps even (about 2 to 3 mm)","Architrave and skirting mitres tight"]},
    "joist-floor":{hours:5,marks:["Joist centres match the drawing","Tops of the joists level","Trimmed opening correctly formed and fixed","Strutting or noggins fitted","Boards fixed properly, access panel removable"]},
    "stair-mockup":{hours:5,marks:["Rise and going match the drawing","Strings level and secure","Newels plumb","Handrail at the right height","Spindle gaps under 100 mm"]},
    "second-fix":{hours:4,marks:["Window board scribed tight to the wall","Boxing-in panel removable for access","Skirting internal scribe and external mitre tight","Unit level and securely fixed","No hammer marks or damage to the finish"]},
    "roof-cladding":{hours:6,marks:["Plumb and seat cuts accurate to the pitch","Rafters at the right centres","Eaves and verge details correct","Cladding boards level with even spacing","Ventilation gaps left where needed"]},
    "joint-board":{hours:5,marks:["Marking out accurate and knife-lined","Each joint fits without gaps","Joints square and flush","No tear-out or splitting","Tools used safely and kept sharp"]},
    "casement":{hours:6,marks:["Setting-out rod accurate to the drawing","Joints tight and square","Glazing rebate the right size","Casement opens and closes freely","Ironmongery fitted straight and working"]},
    "door-frame":{hours:6,marks:["Frame square (diagonals equal)","Joints tight","Door fits with even gaps","Hinges and latch fitted neatly","Door swings without binding"]},
    "mini-stair":{hours:6,marks:["Rise and going match the drawing","Housings tight on the treads and risers","Flight square and solid","Spindles evenly spaced, gaps under 100 mm","Tools and machines used safely"]},
    "unit":{hours:5,marks:["Cutting list worked out correctly","Carcass square (diagonals equal)","Joints strong and flush","Shelf adjusts and sits level","Door hung straight, gaps even"]},
    "l3-arch":{hours:6,marks:["Setting out on the board accurate: centre, radius, springing line","Voussoirs even with radial joints","Rise matches the drawing","Arch face in line and plumb","Turning piece removed without damage"]},
    "l3-curve":{hours:5,marks:["Radius matches the template all the way along","Perpends even round the curve","Splay angle right","Level and to gauge","Cuts neat"]},
    "l3-setting-out":{hours:3,marks:["Datum set and transferred correctly","Corners square: diagonals equal","Openings marked in the right places","Profiles and lines secure","Method statement clear and in order"]},
    "l3-repair":{hours:4,marks:["Cause of the damage identified","Damaged bricks cut out without disturbing the rest","New bricks and mortar match","Bond and joint finish match","Work area kept safe throughout"]},
    "l3-chimney":{hours:6,marks:["Set out to the drawing, square and plumb","Projections even","Flue or core kept clear and to size","Weathering details (DPCs, trays, flashings) shown correctly","Joints finished and clean"]}
  };
  Object.values(T).forEach(list=>list.forEach(t=>{const m=more[t.id];if(m)Object.assign(t,m)}));
  const add={
    bricklayer:[
      {id:"br-cutting",hours:1,title:"Cutting practice: bats, closers and a raking cut",skills:["Cutting bricks","Raking cuts"],
       brief:"Cut a half bat, a three-quarter bat, a queen closer and a 45° raking cut, each to within 3 mm.",
       steps:["Put on eye protection and gloves, and set up a safe cutting area","Mark each cut all round the brick with a pencil and square","Score all round with the bolster and club hammer","Cut with one firm strike on the waste side","Check each piece against its size and tidy the edges"],
       check:"Show your tutor the four pieces and how you marked them.",
       marks:["Half bat 102.5 mm (within 3 mm)","Three-quarter bat 160 mm (within 3 mm)","Queen closer cut straight along its length","Raking cut at 45° and clean","Eye protection worn for every cut"]},
      {id:"br-mortar",hours:1,title:"Mix mortar to a ratio",skills:["Mortar mixing","Materials"],
       brief:"Gauge and mix two batches of 1:6 mortar that match in colour and workability.",
       steps:["Check the bags: cement type, use-by date, sand clean","Gauge 1 part cement to 6 parts sand with gauge boxes or buckets, not shovels","Mix dry until the colour is even","Add water and plasticiser a little at a time","Mix a second batch the same way and compare"],
       check:"Ask your tutor to compare your two batches.",
       marks:["Measured by volume, not by the shovel","Dry mix an even colour before water","Workable: holds on the trowel, not too wet","Both batches the same colour","Mixer or board cleaned straight after"]},
      {id:"br-quoin",hours:3,title:"Build a quoin and stopped end to 12 courses",skills:["Setting out a solid wall","Brick bonds","Cutting bricks"],
       brief:"Build a half-brick quoin (corner) and a stopped end up to 12 courses, racked back, using a gauge rod.",
       steps:["Set out the corner square with 3-4-5","Mark a gauge rod at 75 mm a course","Build the quoin up, racking back each course","Build the stopped end with half bats on alternate courses","Check level, plumb and gauge every few courses"],
       check:"Ask your tutor to check the corner with the gauge rod, a level and a square.",
       marks:["Corner square","Gauge right: 12 courses = 900 mm","Plumb on both faces of the quoin","Racking back even","Stopped end plumb with halves on alternate courses"]},
      {id:"br-set-cavity",hours:2,title:"Set out a cavity wall with openings (no building)",skills:["Cavity wall setting out","Materials"],
       brief:"From a drawing, set out a cavity wall with a door and a window: profiles, lines, gauge rod and opening positions.",
       steps:["Read the drawing: overall size, cavity width and the openings","Fix profiles at each end and strike the lines for both leaves","Check square with 3-4-5 and the diagonals","Mark the openings on the lines, sized to whole bricks where you can","Make a gauge rod showing DPC level, sill and head heights"],
       check:"Ask your tutor to check your lines and opening positions before anyone builds on them.",
       marks:["Both leaves and the cavity the right width","Diagonals equal","Openings in the right place and size","Gauge rod shows DPC, sill and head","Profiles secure and lines tight"]},
      {id:"br-tray",hours:3,title:"Lintel, cavity tray and weep holes over an opening",skills:["Lintels","Cavity wall construction","Materials"],
       brief:"Bed a lintel over an opening, then fit a stop-ended cavity tray and weep holes above it.",
       steps:["Check the lintel is the right type and length for the opening and cavity","Bed it level with the right bearing each end","Fit the cavity tray so it laps the lintel and steps down to the outer leaf","Stop the ends of the tray","Leave weep holes over the lintel (at least two)"],
       check:"Ask your tutor to check the bearing, the tray laps and the weep holes.",
       marks:["Lintel level with at least 150 mm bearing each end","Tray falls to the outer leaf","Tray stop-ended","At least two weep holes, clear of mortar","Cavity clean"]},
      {id:"br-broken",hours:3,title:"Broken bond panel",skills:["Brick bonds","Setting out a solid wall","Cutting bricks"],
       brief:"Set out and build a panel whose length doesn't work in whole bricks, placing the broken bond in the middle.",
       steps:["Dry bond the first course to find the leftover","Put the broken bond (a cut brick) in the middle, the same every other course","Build 6 courses, keeping perpends in line","Keep cuts no smaller than a quarter brick","Finish the joints"],
       check:"Ask your tutor to check where the broken bond sits and your perpends.",
       marks:["Broken bond in the middle, not at the ends","Same position every other course","Perpends in line","No cut smaller than a quarter brick","Level, plumb and to gauge"]},
      {id:"br-protect",hours:1,title:"Protect finished brickwork",skills:["Joint protection","Materials"],
       brief:"Cover and protect a finished panel against rain, frost and damage, and explain what each part stops.",
       steps:["Check the forecast and decide what protection is needed","Brush the wall down before covering","Cover the top and faces with sheeting, weighted so it can't blow off","Protect corners and sills from knocks","Explain to your tutor when you'd use frost protection and why"],
       check:"Ask your tutor to check the covering and talk it through with you.",
       marks:["Wall clean before covering","Top and faces fully covered","Sheeting held down safely","Arrises and sills protected","Can explain rain and frost damage"]},
      {id:"br-replace",hours:2,title:"Cut out and replace a brick",skills:["Brick repairs","Mortar mixing","Jointing styles"],
       brief:"On an existing practice wall, cut out one damaged brick and replace it so it matches.",
       steps:["Choose a brick and mortar colour to match","Drill and cut out the old brick without damaging those around it","Clean out the old mortar from the hole","Butter the new brick all round and slide it in","Point up to match the existing joint"],
       check:"Ask your tutor to check how cleanly you cut out and how well it matches.",
       marks:["Surrounding bricks undamaged","Hole cleaned out properly","New brick flush with the face","Joints full with no gaps","Joint finish matches the wall"]},
      {id:"br-repoint",hours:2,title:"Rake out and repoint a panel",skills:["Brick repairs","Jointing styles","Mortar mixing"],
       brief:"Rake out a square metre of weathered joints and repoint it to match the rest of the wall.",
       steps:["Look at the existing joint finish and mortar colour","Rake out to about 15 mm deep, square at the back, without chipping the arrises","Brush out the dust and dampen the joints","Mix a mortar no stronger than the original and fill the perpends, then the beds","Finish to match once the mortar is thumb-print hard, then brush off"],
       check:"Ask your tutor to compare your panel with the wall around it.",
       marks:["Raked out to an even depth, square at the back","Brick edges not chipped","Joints full with no hollows","Finish and colour match the wall","Face clean with no smears"]}
    ],
    site:[
      {id:"sc-door",hours:4,title:"Hang an internal door",skills:["Doors"],
       brief:"Hang an internal door in a lining with three hinges and fit a tubular latch.",
       steps:["Check the door fits the lining and plane to size","Mark the hinge positions and cut the recesses","Fit the hinges and hang the door","Mark and fit the latch and keep","Adjust so the gaps are even and the door closes smoothly"],
       check:"Ask your tutor to check the gaps and the latch.",
       marks:["Gaps even: about 2 to 3 mm","Hinge recesses flush","Door doesn't bind or spring open","Latch engages first time","No damage to the door or lining"]},
      {id:"sc-skirt",hours:2,title:"Skirting: a scribed internal and a mitred external corner",skills:["Skirting and architrave"],
       brief:"Fit skirting round a corner board with one scribed internal corner and one mitred external corner.",
       steps:["Measure each length","Cut the first length square into the internal corner","Scribe the second length to it","Cut the external mitre","Fix with the right fixings and fill the holes"],
       check:"Ask your tutor to check the scribe and the mitre.",
       marks:["Scribe tight with no gap","Mitre tight and square","Lengths right, no gaps at the ends","Fixings secure and filled","Top edge level"]},
      {id:"sc-arch",hours:2,title:"Architrave a door lining",skills:["Skirting and architrave","Doors"],
       brief:"Fit a set of architraves to a door lining with a consistent margin and tight mitres.",
       steps:["Mark a margin (about 5 mm) round the lining","Cut and fit the head first","Cut the leg mitres to meet the head","Fix to the lining and stud","Fill and sand the nail holes"],
       check:"Ask your tutor to check the margins and mitres.",
       marks:["Margin even all round","Mitres tight","Legs plumb","Fixings secure","No splits or hammer marks"]},
      {id:"sc-board",hours:2,title:"Window board with notched horns",skills:["Window boards"],
       brief:"Measure, cut, notch and fit a window board with horns returned round the reveals.",
       steps:["Measure the reveal width and depth","Mark the horns and notches","Cut the board and return the nosing on the horns","Fit it level, scribed to the frame","Fix and fill"],
       check:"Ask your tutor to check the fit to the frame and the level.",
       marks:["Board level","Scribed tight to the window frame","Horns even both sides","Nosing returns neat","Fixed securely"]},
      {id:"sc-box",hours:3,title:"Box in a pipe run",skills:["Service encasement"],
       brief:"Box in a vertical and a horizontal pipe run with a removable access panel.",
       steps:["Check the pipes and the clearance needed round them","Fix battens to the wall and floor","Cut and fit the boxing panels","Make one panel removable with screws","Fit a trim where it meets the skirting"],
       check:"Ask your tutor to check the access panel and the finish.",
       marks:["Clearance left round the pipes","Framework straight and secure","Access panel removable","Joints tight and flush","Fixings kept clear of the pipes"]},
      {id:"sc-partition",hours:4,title:"Stud partition",skills:["Partition walls","Structural carcassing"],
       brief:"Build a straight timber stud partition with head and sole plates, studs and noggins.",
       steps:["Mark the head and sole plate positions from the drawing","Fix the plates plumb over each other","Cut and fix the studs at the centres given","Fit noggins in a line","Check plumb and line"],
       check:"Ask your tutor to check plumb, straightness and stud centres.",
       marks:["Plates plumb over each other","Studs at the right centres (400 or 600)","Studs plumb","Noggins in a straight line","Fixed securely, no splits"]},
      {id:"sc-rafters",hours:3,title:"Cut a pair of rafters",skills:["Roofs"],
       brief:"Work out the rafter length from the span and pitch, then mark and cut a pair with plumb and seat cuts.",
       steps:["Work out the rise and rafter length from the span and pitch","Make a pattern rafter","Mark the plumb and seat (birdsmouth) cuts","Cut the pair from the pattern","Offer them up to a ridge and plate to check the fit"],
       check:"Ask your tutor to check your working out and the fit.",
       marks:["Rafter length worked out correctly","Plumb cut at the right angle","Birdsmouth no deeper than a third of the rafter","Both rafters the same","Sits tight on the plate and ridge"]},
      {id:"sc-unit",hours:3,title:"Fit a wall unit level",skills:["Units and fitments"],
       brief:"Mark a level line and hang a wall unit on brackets, level and plumb, with the door adjusted.",
       steps:["Mark a level line at the right height","Check for pipes and cables before drilling","Fix the brackets","Hang and level the unit","Adjust the door hinges so it hangs straight"],
       check:"Ask your tutor to check level and plumb.",
       marks:["Unit level and plumb","Fixed securely","Cable and pipe check done before drilling","Door adjusted straight","No damage to the unit"]},
      {id:"sc-rail",hours:4,title:"Handrail and spindles",skills:["Handrails and spindles","Stairs"],
       brief:"Fit a handrail between newels at the right height and space spindles evenly.",
       steps:["Mark the handrail height above the pitch line","Cut and fit the handrail to the newels","Work out the spindle spacing so gaps are under 100 mm","Cut the spindles to the rake","Fix the spindles and infill"],
       check:"Ask your tutor to check the height and the gaps.",
       marks:["Handrail at the right height","Spindle gaps under 100 mm","Spindles plumb","Rake cuts tight","Everything secure"]},
      {id:"sc-clad",hours:3,title:"Timber cladding panel",skills:["Cladding"],
       brief:"Fix battens and shiplap cladding to a test panel with even spacing and a ventilation gap.",
       steps:["Fix a breather membrane and counter battens","Set out the boards so the top and bottom work out","Fix the first board level","Fix the rest with the right fixings","Finish the edges and leave the ventilation gap"],
       check:"Ask your tutor to check level and fixings.",
       marks:["First board level","Even overlap","Fixings the right type, in line","Ventilation gap left","Ends and edges neat"]},
      {id:"sc-joists",hours:4,title:"Joist floor with a trimmed opening",skills:["Floor joists","Structural carcassing"],
       brief:"Lay a small bay of floor joists on hangers, with a trimmed opening and a row of strutting.",
       steps:["Mark the joist centres on the wall plate or ledger from the drawing","Fix the hangers level and in line","Cut and fit the joists, crown up","Form the opening with trimmer and trimming joists, doubled where the drawing shows","Fit herringbone or solid strutting and check the tops are level"],
       check:"Ask your tutor to check the centres, the level and the trimmed opening.",
       marks:["Joist centres match the drawing","Joists crown up and tops level","Hangers fully nailed and tight to the joist","Trimmed opening the right size and doubled up","Strutting fitted tight in a straight line"]}
    ],
    joiner:[
      {id:"bj-rod",hours:2,title:"Cutting list and setting-out rod",skills:["Drawings","Materials"],
       brief:"From a drawing, produce a setting-out rod and a cutting list for a small framed door.",
       steps:["Read the drawing and list every part","Draw the rod full size: heights and widths","Mark the joints on the rod","Write the cutting list with finished and sawn sizes","Check the rod against the drawing"],
       check:"Ask your tutor to check your rod and list.",
       marks:["Rod full size and to the drawing","Joints shown correctly","Cutting list has every part","Allowances added for machining","Neat and readable"]},
      {id:"bj-mt",hours:3,title:"Through mortise and tenon by hand",skills:["Woodworking joints"],
       brief:"Mark out and cut a through mortise and tenon by hand, wedged.",
       steps:["Mark out with a mortise gauge set to the chisel","Chop the mortise from both sides","Saw the tenon cheeks and shoulders","Fit it without forcing","Cut wedges and wedge it"],
       check:"Ask your tutor to check the fit and the shoulders.",
       marks:["Marking out accurate","Mortise square and clean","Shoulders tight both sides","Joint square","Wedges tight, no splits"]},
      {id:"bj-dovetail",hours:3,title:"Lapped dovetail drawer front",skills:["Woodworking joints"],
       brief:"Cut lapped dovetails joining a drawer side to a drawer front.",
       steps:["Mark out the tails","Cut the tails","Mark the pins from the tails","Cut the pins","Fit and glue"],
       check:"Ask your tutor to check the fit.",
       marks:["Tails evenly spaced","No gaps between tails and pins","Lap thickness even","Joint square","No tear-out"]},
      {id:"bj-machine",hours:2,title:"Prepare timber to size on machines (supervised)",skills:["Fixed machinery","Materials"],
       brief:"With your tutor, face, edge and thickness timber to a set size on the planer and thicknesser.",
       steps:["Check the timber for defects and nails","Check the guards and setting with your tutor","Face and edge on the surface planer","Thickness to size","Check sizes and square"],
       check:"Your tutor must supervise the machines.",
       marks:["Safety checks done first","Guards set properly","Face and edge square","To size within 0.5 mm","Hands kept clear, push sticks used"]},
      {id:"bj-lock",hours:2,title:"Fit a mortice lock and handles",skills:["Ironmongery","Timber doors"],
       brief:"Fit a mortice lock or latch and lever handles to a door, with the keep in the frame.",
       steps:["Mark the lock height and centre line","Drill and chop the mortice","Fit the lock flush","Drill for the spindle and key","Fit the handles and the keep"],
       check:"Ask your tutor to check it locks and latches smoothly.",
       marks:["Lock at the right height","Face plate flush","Spindle and key holes lined up","Latches and locks smoothly","Keep fitted flush"]},
      {id:"bj-lining",hours:2,title:"Door lining set",skills:["Door frames and linings","Woodworking joints"],
       brief:"Make a door lining set for a standard internal door, with the head housed into the legs.",
       steps:["Measure the opening width and height at three points and use the smallest","Cut the legs and head to length, allowing for the housings and the floor","Mark and cut the housings in the legs with a saw and router or chisel","Assemble with glue and screws, checking the diagonals","Fix a temporary brace across the bottom so it stays square until it's fitted"],
       check:"Ask your tutor to check the diagonals and the housings before it goes in.",
       marks:["Sizes worked out from the smallest measurement","Housings tight with no gaps","Diagonals equal (square)","Head and legs flush on the face","Brace fitted so it can't rack"]},
      {id:"bj-router",hours:2,title:"Housings with a router and jig",skills:["Power tools","Woodworking joints"],
       brief:"Make a simple jig and cut stopped housings for a shelf with a hand-held router.",
       steps:["Check the router, lead, cutter and base before plugging in","Make a straight-edge jig and clamp it to the line","Set the depth of cut and do a test cut on scrap","Cut the housings in two or three shallow passes, feeding against the rotation","Square the stopped ends with a chisel and test the shelf fit"],
       check:"Ask your tutor to check your set-up before your first cut.",
       marks:["Router and lead checked before use","Jig clamped and square to the edge","Depth even all along","Housings tight on the shelf, square stopped ends","Unplugged before changing the cutter"]},
      {id:"bj-defects",hours:1,title:"Timber selection and defects",skills:["Materials","Drawings"],
       brief:"Go through a stack of timber, name the defects in each piece, check the moisture and choose what's fit for a job.",
       steps:["Look at each piece for knots, shakes, splits, wane and sap stain","Sight along it for bow, spring, cup and twist","Take moisture readings in three places with a meter","Sort into use, cut round and reject, and label each piece","Read a cutting list and pick the best pieces for it, explaining why"],
       check:"Ask your tutor to go through your choices with you.",
       marks:["Defects named correctly","Distortion (bow, spring, cup, twist) spotted","Moisture readings taken and recorded","Rejects set aside with a reason","Best timber picked for the cutting list"]},
      {id:"bj-sash",hours:4,title:"Casement sash with glazing bars",skills:["Timber windows","Woodworking joints"],
       brief:"Make a small casement sash with a rebate for glass and a single glazing bar, from a rod.",
       steps:["Mark out the stiles and rails from your rod","Cut the mortise and tenons, with scribed or mitred mouldings","Cut the rebate and fit the glazing bar","Glue up and check the diagonals","Clean up and fit glazing beads"],
       check:"Ask your tutor to check the joints, rebate and square.",
       marks:["Marking out matches the rod","Joints tight, mouldings meet cleanly","Rebate even and the right depth","Sash square and flat (not in wind)","Beads fit with tight mitres"]},
      {id:"bj-string",hours:4,title:"Housed string section with spindles",skills:["Straight staircases","Staircase spindles"],
       brief:"Make a short section of wall string housed for three treads and risers, with a matching handrail section drilled for spindles.",
       steps:["Work out the rise and going and make a pitch board","Mark the housings on the string with the pitch board and a margin template","Rout or cut the tapered housings for the treads, risers and wedges","Fit the treads and risers with wedges and glue blocks","Mark and drill the handrail for spindles with gaps under 100 mm"],
       check:"Ask your tutor to check the housings, the pitch and the spindle spacing.",
       marks:["Rise and going match the drawing","Margin even along the string","Housings tight with wedges driven","Treads level and square to the string","Spindle gaps under 100 mm"]},
      {id:"bj-base",hours:4,title:"Floor unit with a drawer",skills:["Wall and floor units","Woodworking joints","Ironmongery"],
       brief:"Make a small floor unit on a plinth with a drawer on runners.",
       steps:["Work out the cutting list from the drawing","Cut and join the carcass with a plinth and a back","Make the drawer box with housed or dovetailed corners","Fit the runners so the drawer runs level","Fit the drawer front with even gaps and a handle"],
       check:"Ask your tutor to check square and how the drawer runs.",
       marks:["Carcass square and level on its plinth","Drawer box square","Drawer runs smoothly with no rattle","Front gaps even","Handle fitted straight and central"]}
    ],
    trowel3:[
      {id:"l3-plinth",hours:4,title:"Plinth and corbel course",skills:["Decorative work","Masonry structures"],
       brief:"Build a one-brick panel with a plinth course near the base and a two-course corbel near the top.",
       steps:["Set out the panel from the drawing and build the base courses to gauge","Lay the plinth bricks, keeping the splay level and in line","Continue the main wall above the plinth, set back the right amount","Build up to the corbel and project each course by no more than a third of the brick","Finish the joints and check the projections with a straight edge"],
       check:"Ask your tutor to check the plinth line and the corbel projections.",
       marks:["Plinth level and straight along its length","Set-back above the plinth even","Corbel projections even (no more than a third of a brick each)","Wall plumb and to gauge","Joints finished neatly and face clean"]},
      {id:"l3-coping",hours:3,title:"Brick-on-edge coping with creasing",skills:["Decorative work","Masonry structures"],
       brief:"Finish a garden wall with a double tile creasing and a brick-on-edge coping.",
       steps:["Check the top of the wall is level and clean","Lay the first course of creasing tiles with an even overhang each side","Lay the second course, breaking joint with the first","Lay the brick-on-edge coping to a line, with a tight joint every brick","Tighten the ends (a cut or a dog-leg brick) and point up"],
       check:"Ask your tutor to check the overhang, the line and the ends.",
       marks:["Creasing overhang even both sides","Tile joints broken between courses","Coping straight and level to the line","Joints full and tight, ends secure","Face and tiles clean"]},
      {id:"l3-semi",hours:2,title:"Set out a semicircular arch on a board",skills:["Arches","Setting out"],
       brief:"Set out a semicircular arch full size on a board: springing line, centre, curves and voussoirs.",
       steps:["Draw the springing line and mark the span on it","Find the centre and draw the inside (intrados) curve with a trammel","Draw the outside (extrados) curve one brick deeper","Divide the extrados into an odd number of equal voussoirs so a key brick sits at the crown","Draw each joint line back to the centre and label the key brick"],
       check:"Ask your tutor to check your setting out before it's used for a turning piece.",
       marks:["Springing line level and span right","Radius correct for the span","Voussoirs equal, an odd number","Joints radial (all to the centre)","Key brick central and drawing labelled"]},
      {id:"l3-cladding",hours:4,title:"Brick cladding to a timber-frame mock-up",skills:["Masonry cladding","Masonry structures"],
       brief:"Build the brick outer leaf to a timber-frame panel, fixing the ties to the studs and keeping the cavity clear.",
       steps:["Check the frame, breather membrane and the stud lines marked on it","Set out the brickwork with the right cavity from the frame","Build to the first tie course and fix flexible ties into the studs","Keep building, fixing ties at the spacing given and allowing for the frame to shrink at openings and the top","Keep the cavity clear and check plumb, level and gauge as you go"],
       check:"Ask your tutor to check the tie fixings, the cavity and the gaps left for shrinkage.",
       marks:["Ties fixed into the studs, not just the sheathing","Ties at the right spacing, sloping down to the brick","Cavity the right width and clear of mortar","Shrinkage gaps left at the top and under sills","Level, plumb and to gauge"]},
      {id:"l3-plan",hours:1,title:"Plan a week's work",skills:["Planning work","Drawings and information"],
       brief:"From a drawing and a brief, plan a week's bricklaying for a small gang: order, labour, materials and plant.",
       steps:["Read the drawing and list the jobs in the order they must happen","Work out how many bricks, blocks and bags you need (with waste)","Put each job on a simple day-by-day programme","Note the labour, plant and deliveries needed each day","Write down what could hold the job up and what you'd do about it"],
       check:"Talk your plan through with your tutor.",
       marks:["Jobs in a sensible order","Quantities worked out with waste added","Programme realistic for the gang","Deliveries and plant planned in time","Risks and hold-ups thought through"]},
      {id:"l3-method",hours:1,title:"Write a method statement",skills:["Methods of work","Working relationships"],
       brief:"Write a method statement for one task, such as building a chimney stack from a scaffold.",
       steps:["Describe the task and where it happens","List the hazards and the controls for each","Write the steps in order, with who does what","List the PPE, tools, plant and materials","Say who needs to know (supervisor, other trades) and how you'll tell them"],
       check:"Ask your tutor to read it and tell you what's missing.",
       marks:["Task and location clear","Hazards matched to controls","Steps in a safe, logical order","PPE and equipment listed","Other trades and supervisor included"]},
      {id:"l3-talk",hours:1,title:"Give a toolbox talk",skills:["Working relationships","Methods of work"],
       brief:"Prepare and give a 5-minute toolbox talk to your group, such as working at height or manual handling.",
       steps:["Pick a topic that matters on your site","Write three to five key points and a real example","Give the talk in about five minutes","Ask questions to check people understood","Keep a signed record of who attended"],
       check:"Ask your tutor for feedback on how you came across.",
       marks:["Topic relevant to the work","Points clear and correct","Kept to about five minutes","Checked understanding with questions","Attendance recorded"]},
      {id:"l3-squint",hours:4,title:"Squint quoin",skills:["Curved and splayed walls","Setting out"],
       brief:"Set out and build a 45° squint quoin (an angle that isn't square) using squint bricks or cut bricks.",
       steps:["Set out the angle on the base with a bevel or from the drawing","Dry bond the first two courses to work out the bond at the angle","Build the quoin with squint specials or neatly cut bricks","Rack back both walls, checking the angle every few courses","Finish the joints and check plumb on the angle"],
       check:"Ask your tutor to check the angle, the bond and plumb on the arris.",
       marks:["Angle matches the drawing","Bond correct at the quoin, no straight joints","Arris plumb","Level and to gauge","Cuts clean and joints finished"]},
      {id:"l3-repoint",hours:3,title:"Survey and repair a damaged panel",skills:["Repairs","Methods of work","Drawings and information"],
       brief:"Survey a damaged practice panel, record the defects, write the repair method and carry out part of it.",
       steps:["Record the defects: cracks, spalled bricks, eroded joints, with a sketch","Work out the likely cause of each one","Write the repair method and choose bricks and mortar to match","Cut out and replace two bricks and repoint around them","Compare the repair with the rest and note what you'd do differently"],
       check:"Ask your tutor to read your survey and check the repair.",
       marks:["Defects recorded on a sketch","Causes explained sensibly","Mortar no stronger than the original","Repair matches colour, bond and joint","Clean cut-out, surrounding bricks undamaged"]},
      {id:"l3-fireplace",hours:5,title:"Fireplace opening with a gather",skills:["Chimneys and fireplaces","Drawings and information","Setting out"],
       brief:"Build a fireplace recess with a lintel and the gather over it to take a flue liner, from a drawing.",
       steps:["Read the drawing: opening size, hearth and flue size","Set out the chimney breast and jambs","Build the jambs and bed the fireplace lintel","Corbel the gather in evenly to the flue size","Set the first flue liner socket up with the joint sealed"],
       check:"Ask your tutor to check the opening, the gather and the liner.",
       marks:["Opening and jambs to the drawing","Lintel level with the right bearing","Gather even both sides and smooth inside","Flue liner the right way up, joint sealed","Plumb and to gauge"]}
    ]
  };
  Object.keys(add).forEach(k=>{T[k]=(T[k]||[]).concat(add[k])});
  Object.values(T).forEach(list=>list.forEach(t=>{t.time=t.hours+(t.hours===1?" hour":" hours");t.marks=(t.marks||[]).concat(SAFE)}));
})();
