/* Site Showdown: the encounters (showdown.js plays them).
   Each encounter: [type, tier (1 easy to 3 hard), name, question, [right move, why], [wrong move, why], [wrong, why],
   [wrong, why], art]. {n} is the learner's first name ("you" if we don't know it). The right move is always first here
   and shuffled in play. Every wrong move says why, so each mistake teaches something.
   Types: fire, ppe, coshh, sign, plan, mix, brick, wood, site, maths, english, edi. Trade types are only used for the
   learner's trade (mix and brick: bricklaying; wood: carpentry and joinery); maths and English only if they're on.
   Facts are UK: extinguisher bands (BS EN 3, BS 7863), safety signs (BS EN ISO 7010), 110 V site tools, the 1-in-4
   ladder rule, CoSHH, RIDDOR, the Equality Act 2010.
   Bosses: steps in the order they happen. Boss 1 has 1 step, boss 2 has 2 steps… up to 5. key gives which steps to
   use first, so a short boss still keeps the most important ones (in the order they happen); intro sets the scene. */
window.EVIA_SHOWDOWN={
  foes:[
    /* ---------- Fires ---------- */
    ["fire",1,"Timber Blaze","A pile of timber offcuts has caught fire. Which extinguisher will {n} grab?",["Water (red band)","Water cools burning wood, paper and fabric: class A fires."],["CO2 (black band)","CO2 is for electrical fires. It doesn’t cool the wood, so it can flare up again."],["Fire blanket","A blanket is for a small pan fire or someone’s clothes, not a pile of burning timber."],["Kick it apart","Spreading burning timber spreads the fire."],"wood"],
    ["fire",1,"Sparky Socket","Flames are coming from a transformer on site. What will {n} use?",["CO2 (black band)","CO2 smothers the fire, leaves nothing behind and is safe on electrical equipment."],["Water (red band)","Water conducts electricity. You could be electrocuted."],["Foam (cream band)","Standard foam is water-based, so it isn’t safe on electrics."],["Wet chemical (yellow band)","Wet chemical is for cooking oil fires."],"elec"],
    ["fire",2,"Petrol Flare","Petrol spilled by the mixer has caught fire. What will {n} use?",["Foam (cream band)","Foam blankets burning liquids like petrol: class B fires."],["Water (red band)","Water spreads burning petrol and makes it worse."],["Wet chemical (yellow band)","Wet chemical is for cooking oil, not petrol."],["Fire blanket","A blanket won’t cover a spreading petrol spill."],"liquid"],
    ["fire",2,"Pan Flame","In the site canteen, a pan of cooking oil is on fire. What will {n} use?",["Wet chemical (yellow band)","Wet chemical cools and seals burning cooking oil: class F fires."],["Water (red band)","Water on burning oil causes a fireball."],["Foam (cream band)","Foam isn’t made for cooking oil fires."],["CO2 (black band)","The blast from CO2 can spread burning oil, and it can reignite."],"oil"],
    ["fire",2,"Gas Jet","A leak from a gas bottle has caught light. What will {n} do first?",["Shut off the gas, if it’s safe","Stop the fuel first. Putting out a gas flame while gas still leaks can cause an explosion."],["Spray it with water","Water won’t stop the gas, and the leak carries on."],["Throw a blanket over it","Gas builds up under the blanket."],["Try to blow it out","You can’t blow out a gas jet, and the gas keeps leaking."],"gas"],
    ["fire",3,"Swarf Spark","Metal swarf from cutting has caught fire. Which extinguisher is right?",["Specialist dry powder","Burning metals (class D) need a special powder."],["Water (red band)","Water on burning metal can explode."],["CO2 (black band)","CO2 won’t put out burning metal."],["Foam (cream band)","Foam is water-based: dangerous on burning metal."],"metal"],
    ["fire",1,"Smoke Sneak","{n} spots smoke coming from under a store room door. What first?",["Raise the alarm","Everyone needs to get out, and the fire service needs calling. Alarm first."],["Finish the course first","Every second counts in a fire."],["Open the door to look","Opening the door can feed the fire with air."],["Film it for the group chat","Raise the alarm. Filming wastes time and puts you at risk."],"wood"],
    ["fire",1,"Band of Red","Which colour band is on a water extinguisher?",["Red","Water extinguishers are all red."],["Black","Black is CO2."],["Cream","Cream is foam."],["Yellow","Yellow is wet chemical."],"wood"],
    ["fire",2,"Black Band","An extinguisher has a black band. What’s inside?",["CO2","Black means carbon dioxide: for electrical fires."],["Water","Water is all red."],["Foam","Foam has a cream band."],["Dry powder","Dry powder has a blue band."],"elec"],
    ["fire",2,"Cream Band","An extinguisher has a cream band. What’s inside?",["Foam","Cream means foam: good for burning liquids like petrol."],["CO2","CO2 has a black band."],["Water","Water is all red."],["Wet chemical","Wet chemical has a yellow band."],"liquid"],
    ["fire",2,"Yellow Band","An extinguisher has a yellow band. What’s it for?",["Cooking oil fires","Yellow is wet chemical, for class F fires like a chip pan."],["Electrical fires","That’s CO2, with a black band."],["Petrol fires","That’s foam, with a cream band."],["Burning metal","That’s specialist powder."],"oil"],
    ["fire",1,"Siren Wail","The fire alarm is going off. Where will {n} go?",["The fire assembly point","Go straight there, so you can be counted and nobody goes looking for you."],["Back to the van for tools","Leave everything. Tools can be replaced."],["The canteen","Go to the assembly point so you’re counted."],["Wait to see if it’s real","Treat every alarm as real."],"wood"],
    ["fire",2,"Fire Triangle","A fire needs heat, fuel and one more thing. What is it?",["Oxygen","Take away heat, fuel or oxygen and the fire goes out."],["Water","Water puts some fires out: it isn’t part of the triangle."],["Smoke","Smoke is what a fire makes."],["Wind","Wind can feed a fire with oxygen, but oxygen is the answer."],"wood"],
    ["fire",3,"PASS Master","Using an extinguisher, what’s the right order?",["Pull, aim, squeeze, sweep","Pull the pin, aim at the base, squeeze the handle, sweep side to side."],["Aim, pull, sweep, squeeze","Pull the pin first, or it won’t fire."],["Squeeze, pull, aim, sweep","It won’t work until the pin is out, and you need to aim first."],["Sweep, squeeze, aim, pull","That’s back to front."],"wood"],

    /* ---------- Hazards and PPE ---------- */
    ["ppe",1,"Dust Devil","Cutting blocks with a disc cutter kicks up silica dust. What will {n} wear?",["FFP3 mask, face-fit tested","Silica dust damages lungs for life. FFP3 is the right filter, and it has to fit your face."],["Ear defenders","They protect your hearing, not your lungs."],["Hi-vis vest","Hi-vis helps people see you. It doesn’t stop dust."],["Rigger gloves","Gloves protect hands, not lungs."],"dust"],
    ["ppe",1,"Racket","The breaker is deafening. What will {n} put on?",["Ear defenders","Loud noise damages hearing for good. Protect it."],["Safety goggles","Goggles protect eyes, not ears."],["Dust mask","A mask protects lungs, not ears."],["Knee pads","Knee pads protect knees."],"noise"],
    ["ppe",1,"The Dropper","Scaffolders are working above {n}. What protects their head?",["Hard hat","A hard hat protects your head from falling objects."],["Beanie hat","A beanie won’t stop a falling brick."],["Safety goggles","Goggles protect eyes only."],["Hi-vis vest","Hi-vis helps people see you, not your head."],"drop"],
    ["ppe",1,"Splash","Mixing lime can splash into eyes. What will {n} wear?",["Safety goggles","Lime burns eyes. Goggles seal them from splashes."],["Sunglasses","Sunglasses aren’t splash or impact rated."],["Hard hat","A hard hat protects your head, not your eyes."],["Ear defenders","Ear defenders protect hearing."],"splash"],
    ["ppe",1,"Nail Spike","Loose boards with nails are everywhere. What protects {n}’s feet?",["Safety boots with a midsole","Toecaps stop crushing and a midsole stops nails going through."],["Trainers","A nail goes straight through a trainer."],["Everyday work shoes","Without toecaps and a midsole they don’t protect you."],["Knee pads","Knee pads protect knees, not feet."],"nail"],
    ["ppe",1,"Reverser","A dumper is reversing nearby. What helps the driver see {n}?",["Hi-vis clothing","Hi-vis makes you easy to see. Stay out of the way too."],["Dark jacket","Dark clothing makes you harder to see."],["Ear defenders","You need to hear plant moving, and be seen."],["Hard hat only","A hard hat alone doesn’t make you easy to see."],"plant"],
    ["ppe",2,"Cement Burn","{n} is handling wet mortar all day. Which gloves?",["Waterproof nitrile-coated gloves","Wet cement burns skin and causes dermatitis. Waterproof gloves keep it off."],["Cloth rigger gloves","Wet cement soaks through cloth and holds it against your skin."],["Fingerless gloves","Your fingers get covered in cement."],["No gloves, wash later","Cement burns can start before you wash."],"splash"],
    ["ppe",2,"Knee Grinder","{n} is laying blocks at low level for hours. What helps?",["Knee pads","Kneeling for hours damages knees. Pads protect them."],["Safety goggles","Goggles protect eyes."],["Ear defenders","Ear defenders protect hearing."],["A thicker coat","A coat won’t protect your knees."],"nail"],
    ["ppe",2,"Scorcher","It’s a hot summer day on an open roof. What will {n} do?",["Cover up, use sun cream and drink water","Sunburn, heat stroke and skin cancer are real risks on site."],["Take their top off","Bare skin burns and raises skin cancer risk."],["Drink energy drinks only","You need water to stay hydrated."],["Work through without breaks","Heat builds up. Take breaks in the shade."],"sun"],
    ["ppe",2,"Buzz Hands","{n} uses a breaker a lot. What cuts the risk of hand-arm vibration?",["Limit time on it, take breaks, use low-vibration tools","Vibration damages nerves and blood vessels. Less time on the tool means less damage."],["Grip it tighter","A tight grip passes more vibration into your hands."],["Thicker gloves only","Gloves keep hands warm but don’t stop the vibration."],["Use it all day to finish sooner","More time on the tool means more damage."],"noise"],
    ["ppe",3,"Last Line","Where does PPE come in controlling a risk?",["It’s the last line of defence","First remove or reduce the hazard. PPE is for what’s left."],["It’s always the first thing","Getting rid of the hazard comes first."],["It replaces a risk assessment","PPE is chosen because of the risk assessment."],["It’s only needed on big sites","PPE is needed wherever the risk is."],"dust"],

    /* ---------- Substances (CoSHH) ---------- */
    ["coshh",1,"The Acronym","What does CoSHH stand for?",["Control of Substances Hazardous to Health","The regulations for working safely with harmful substances."],["Construction Safety and Health Handbook","Close, but no."],["Control of Site Hazards and Hoists","That’s not it."],["Care of Staff Health and Hygiene","That’s not it."],"drum"],
    ["coshh",2,"Soaker","Wet mortar has soaked through {n}’s sleeve onto their arm. What now?",["Wash it off with clean water straight away","Cement burns get worse the longer it stays on your skin."],["Leave it until break","The burn gets worse all the time it’s on your skin."],["Wipe it with a dry rag and carry on","It leaves cement behind, still burning."],["Rub barrier cream over it","Barrier cream goes on before work, on clean skin."],"drum"],
    ["coshh",2,"Mystery Tin","{n} needs to use a new sealant safely. Where will they look?",["The safety data sheet","It says what the hazards are, what PPE to wear and what to do if something goes wrong."],["Ask a mate","They might not know. Check the data sheet."],["Smell it","Never sniff chemicals."],["The price label","The price doesn’t tell you how to use it safely."],"drum"],
    ["coshh",2,"Silica Cloud","Which of these is a CoSHH hazard when cutting bricks?",["Silica dust","Breathing it in causes silicosis, which can’t be cured."],["Noise","Noise is a hazard, but it isn’t a substance."],["Vibration","Vibration is a hazard, but it isn’t a substance."],["Sunlight","Sunlight isn’t covered by CoSHH."],"drum"],
    ["coshh",3,"Brick Acid","{n} is cleaning brickwork with brick acid. What’s right?",["Gloves, goggles and follow the data sheet","Brick acid burns skin and eyes, and the data sheet says how to use it safely."],["Just be careful","Being careful isn’t enough. Wear the right PPE."],["Mix it stronger to finish quicker","Stronger acid is more dangerous and damages the bricks."],["Use it without reading the label","Always read the label and data sheet first."],"drum"],
    ["coshh",1,"Red Diamond","A tin has a red diamond symbol on it. What does it mean?",["It’s hazardous: read the label","Red diamonds warn of a hazard. The picture inside says which."],["It’s a quality mark","It’s a hazard warning."],["It’s safe to use","It means the opposite."],["It’s a recycling symbol","It’s a hazard warning."],"drum"],

    /* ---------- Safety signs (BS EN ISO 7010) ---------- */
    ["sign",1,"Blue Helmet","What does this sign mean?",["Hard hats must be worn","A blue circle means you must do this."],["No hard hats allowed","A ban would be a red circle with a line."],["Hard hats sold here","Blue circles are instructions."],["Hard hats are optional","Blue means you must."],"hardhat"],
    ["sign",1,"No Smoke","What does this sign mean?",["No smoking","A red circle with a line means don’t do this."],["Smoking area","It’s a ban."],["Smoking allowed after work","It’s a ban at all times."],["Mind the smoke","That would be a yellow warning sign."],"smoke"],
    ["sign",1,"Zap","What does this sign mean?",["Danger: electricity","A yellow triangle warns of a hazard."],["Lightning storm coming","It warns of electricity on site."],["Charging point","It’s a warning."],["Power tools must be used","A must-do sign would be blue."],"bolt"],
    ["sign",1,"Green Cross","What does this sign mean?",["First aid","Green signs show safe conditions: first aid, exits."],["Hospital","It shows where first aid is on site."],["No entry","That would be red."],["Crossroads ahead","It’s the first aid sign."],"cross"],
    ["sign",1,"Red Box","What does this sign mean?",["Fire extinguisher here","Red rectangles show firefighting equipment."],["Fire risk","A fire risk warning would be yellow."],["No fires","A ban would be a red circle with a line."],["Fire exit","Fire exits are green."],"ext"],
    ["sign",2,"Blue Ears","What does this sign mean?",["Ear protection must be worn","A blue circle means you must do this."],["No headphones","A ban would be red."],["Listen for instructions","It’s about protecting your hearing."],["Quiet area","It means wear ear protection."],"ears"],
    ["sign",2,"Blue Goggles","What does this sign mean?",["Eye protection must be worn","A blue circle means you must do this."],["No sunglasses","A ban would be red."],["Look out","A warning would be yellow."],["Eye test here","It means wear eye protection."],"goggles"],
    ["sign",2,"Yellow Triangle","A yellow triangle sign means what?",["Warning: there’s a hazard","Yellow triangles warn you."],["You must do this","That’s a blue circle."],["Don’t do this","That’s a red circle with a line."],["Safe condition","That’s green."],"warn"],
    ["sign",2,"Blue Circle","A blue circle sign means what?",["You must do this","Blue circles are mandatory."],["Warning of a hazard","That’s a yellow triangle."],["Don’t do this","That’s red with a line."],["Where first aid is","That’s green."],"must"],
    ["sign",2,"Red Line","A red circle with a line through it means what?",["Don’t do this","It’s a prohibition sign."],["You must do this","That’s blue."],["Warning","That’s yellow."],["Fire equipment","That’s a red rectangle."],"smoke"],
    ["sign",2,"Green Square","A green square sign means what?",["A safe condition, like first aid or an exit","Green shows where safety is."],["Danger","Danger is yellow."],["You must do this","That’s blue."],["Don’t do this","That’s red."],"cross"],

    /* ---------- Plans and scales ---------- */
    ["plan",1,"Scale Snake","On a 1:50 drawing, 1 mm on paper is how much on site?",["50 mm","At 1:50, everything is 50 times bigger for real."],["5 mm","That would be 1:5."],["500 mm","That would be 1:500."],["1 m","That would be 1:1000."],"plan"],
    ["plan",2,"Long Wall","At 1:50, a wall measures 80 mm on the plan. How long is it really?",["4 m","80 × 50 = 4000 mm, which is 4 m."],["40 m","That’s 80 × 500."],["0.4 m","That’s 80 × 5."],["8 m","That’s 80 × 100."],"plan"],
    ["plan",2,"Hundred Scale","At 1:100, a wall is 45 mm on the plan. How long is it really?",["4.5 m","45 × 100 = 4500 mm, which is 4.5 m."],["45 m","That’s 45 × 1000."],["0.45 m","That’s 45 × 10."],["450 m","Far too long."],"plan"],
    ["plan",2,"Twenty Scale","At 1:20, a lintel is 150 mm on the drawing. How long is it?",["3 m","150 × 20 = 3000 mm, which is 3 m."],["30 m","That’s 150 × 200."],["1.5 m","That’s 150 × 10."],["0.3 m","That’s 150 × 2."],"plan"],
    ["plan",1,"Bird’s Eye","Which drawing shows the building from above?",["Plan","A plan looks down from above."],["Elevation","An elevation shows a face from the side."],["Section","A section is a slice through."],["Detail","A detail is a close-up of one part."],"plan"],
    ["plan",2,"Face Off","Which drawing shows the outside face of a wall?",["Elevation","Elevations show the faces of the building."],["Plan","A plan is from above."],["Section","A section is a slice through."],["Site plan","A site plan shows the whole site from above."],"plan"],
    ["plan",2,"The Slicer","Which drawing is a cut through the building?",["Section","A section shows what’s inside, like cutting a cake."],["Plan","A plan is from above."],["Elevation","An elevation is a face."],["Location plan","That shows where the site is."],"plan"],
    ["plan",3,"Paper Wall","A 6 m wall is drawn at 1:50. How long is it on paper?",["120 mm","6000 ÷ 50 = 120 mm."],["12 mm","That’s 6000 ÷ 500."],["300 mm","That’s 6000 ÷ 20."],["60 mm","That’s 6000 ÷ 100."],"plan"],
    ["plan",1,"Tiny Tray","Which scale shows a small detail, like a cavity tray, best?",["1:5","A small ratio shows things big, so details are clear."],["1:500","Much too small to see details."],["1:1250","That’s for maps of the area."],["1:100","Fine for floor plans, too small for details."],"plan"],

    /* ---------- Mortar mixes (bricklaying) ---------- */
    ["mix",1,"Gauge Goblin","The spec says 1:4. For every bucket of cement, how many buckets of sand?",["4","1:4 means 1 cement to 4 sand."],["1","That would be 1:1."],["3","That would be 1:3."],["5","That would be 1:5."],"tub"],
    ["mix",2,"Lime Lurker","The spec says 1:1:6 cement:lime:sand. How much lime for 2 buckets of cement?",["2 buckets","1 lime for every 1 cement, so 2."],["1 bucket","You need to double it all for 2 buckets of cement."],["6 buckets","6 is the sand for 1 bucket of cement."],["12 buckets","12 is the sand for 2 buckets of cement."],"tub"],
    ["mix",2,"Sand Heap","The spec says 1:1:6. How much sand for 2 buckets of cement?",["12 buckets","6 sand for every 1 cement, so 12 for 2."],["6 buckets","That’s for 1 bucket of cement."],["8 buckets","2 × 6 is 12."],["3 buckets","Much too little sand."],"tub"],
    ["mix",2,"Shovel Slop","Why gauge with buckets instead of counting shovelfuls?",["Every batch stays the same strength and colour","Shovelfuls vary. Buckets keep every mix the same."],["It’s quicker","It’s about getting the same mix each time."],["Shovels are banned","They aren’t. Buckets are just more accurate."],["It uses less cement","It uses the right amount."],"tub"],
    ["mix",1,"Mud Pie","What’s bricklaying mortar made from?",["Cement, sand and water","Plus lime or plasticiser if the spec says."],["Cement and gravel","Gravel is for concrete."],["Plaster and sand","Plaster is for walls inside."],["Clay and water","Mortar needs cement or lime."],"tub"],
    ["mix",2,"Stiff Stuff","The mortar on the board has started to set. What will {n} do?",["Throw it away and mix fresh","Once cement mortar starts to set, adding water weakens it."],["Add water and knock it up","Re-wetting setting mortar makes it weak."],["Add more cement","That won’t undo the setting."],["Use it on the top course","Weak mortar is weak anywhere."],"tub"],
    ["mix",3,"Frost Bite","Frost is forecast tonight. What about today’s brickwork?",["Cover and protect it","Frost can freeze the water in fresh mortar and ruin the joints."],["Leave it open to dry","Frost can still get in."],["Soak it with water","Wet mortar freezes more easily."],["Add salt to the mortar","Salt damages mortar and bricks."],"tub"],
    ["mix",3,"Bubble Trouble","What does plasticiser do in mortar?",["Makes it easier to work","It traps tiny air bubbles, so the mortar spreads better."],["Makes it set faster","That’s an accelerator."],["Makes it waterproof","That’s a waterproofer."],["Changes its colour","That’s a pigment."],"tub"],

    /* ---------- Bricklaying ---------- */
    ["brick",1,"Recess Rex","The joints need a recessed finish. What will {n} use?",["Chariot","A chariot rakes the joint back to a set depth."],["Bucket handle","That makes a half-round finish."],["Pointing trowel","That’s for flush or weather-struck joints."],["Soft brush","A brush tidies the face, it doesn’t rake the joint back."],"wall"],
    ["brick",1,"Weathered Walt","The spec wants weather-struck joints. What will {n} use?",["Pointing trowel","Angled to shed rainwater off the joint."],["Chariot","That makes a recessed joint."],["Bucket handle","That makes a half-round joint."],["Gauge rod","That checks course heights."],"wall"],
    ["brick",1,"Round Rhonda","The joints need a half-round finish. What will {n} use?",["Half-round jointer (bucket handle)","It presses a smooth, curved joint."],["Chariot","That makes a recessed joint."],["Pointing trowel","That makes flush or weather-struck joints."],["Club hammer","That’s for cutting."],"wall"],
    ["brick",1,"Leaning Tower","How will {n} check the wall is upright?",["Spirit level held upright","That checks the wall is plumb."],["Tape measure","A tape checks lengths."],["Line and pins","A line keeps courses straight along the wall."],["Gauge rod","That checks course heights."],"wall"],
    ["brick",1,"Wobbly Course","How will {n} keep each course straight along a long wall?",["Line and pins","Stretched tight between the corners, the line keeps every brick in line."],["Spirit level alone","A level is too short for a long wall."],["By eye","It won’t be accurate."],["Tape measure","A tape checks lengths."],"wall"],
    ["brick",2,"Gauge Ghost","How will {n} check each course is at the right height?",["Gauge rod","It’s marked with the course heights."],["Spirit level","That checks level and plumb."],["Square","That checks corners."],["Line and pins","That keeps courses straight."],"wall"],
    ["brick",2,"Half Bat","How will {n} cut a brick cleanly by hand?",["Club hammer and bolster","Score it, then a sharp tap cuts it cleanly."],["Claw hammer","It isn’t made for cutting bricks."],["Spirit level","That’s for checking level."],["Tape measure","That measures the cut, it doesn’t make it."],"wall"],
    ["brick",2,"Half Lap","In stretcher bond, how much do the bricks overlap?",["Half a brick","Half-bond spreads the load and looks right."],["A quarter of a brick","That’s quarter bond."],["None","Straight joints make a weak wall."],["A whole brick","Then it wouldn’t overlap at all."],"wall"],
    ["brick",2,"English Eddie","Which bond has whole courses of headers and whole courses of stretchers, taking turns?",["English bond","A course of headers, then a course of stretchers."],["Flemish bond","Flemish mixes headers and stretchers in the same course."],["Stretcher bond","All stretchers."],["Stack bond","Straight joints all the way up."],"wall"],
    ["brick",2,"Flemish Fiona","What does each course of Flemish bond have?",["Headers and stretchers taking turns","Header, stretcher, header, stretcher."],["All headers","That’s header bond."],["All stretchers","That’s stretcher bond."],["A header every sixth brick","That’s not Flemish."],"wall"],
    ["brick",2,"Course Counter","A brick is 65 mm high with a 10 mm joint. What’s one course?",["75 mm","65 + 10 = 75 mm."],["65 mm","You need to add the joint."],["85 mm","65 + 10 is 75."],["100 mm","That’s too high."],"wall"],
    ["brick",2,"Tie Tamer","What are wall ties for in a cavity wall?",["Tying the two leaves together","They make the two leaves work as one wall."],["Holding the DPC down","The DPC is bedded in mortar."],["Stopping heat loss","That’s the insulation’s job."],["Levelling the courses","A level does that."],"wall"],
    ["brick",2,"Drip Drop","Why do wall ties have a drip in the middle?",["So water can’t cross the cavity","Water drips off in the cavity instead of running to the inner leaf."],["To hold insulation","Clips hold the insulation."],["To look neat","It’s there for a reason."],["To make them stronger","It’s about water."],"wall"],
    ["brick",2,"Damp Riser","What does the DPC stop?",["Rising damp","Water in the ground can’t soak up through the wall."],["Heat loss","That’s the insulation."],["Noise","It isn’t for sound."],["Cracks","It won’t stop cracks."],"wall"],
    ["brick",3,"Weep Wisp","Weep holes above a cavity tray let what out?",["Water","Water on the tray runs out through the weep holes."],["Heat","They aren’t for heating."],["Mortar","Mortar should be kept out of the cavity."],["Insects","They let water out. Some have covers to keep insects out."],"wall"],
    ["brick",1,"Rain Cloud","Rain is on its way and the brickwork is fresh. What will {n} do?",["Cover it with sheeting","Rain washes out fresh mortar and stains the face."],["Leave it: it’ll dry","Rain can ruin fresh joints."],["Point it later","Protect it now."],["Build faster","Cover it."],"wall"],

    /* ---------- Carpentry and joinery ---------- */
    ["wood",1,"Square Bear","How will {n} check a frame is square?",["Measure the diagonals","If both diagonals are the same, it’s square."],["Spirit level","That checks level and plumb."],["Tape along one side","That gives a length, not square."],["By eye","It won’t be accurate."],"plank"],
    ["wood",1,"Cross Cutter","{n} needs to cut across the grain by hand. Which saw?",["Crosscut saw","Its teeth are made for cutting across the grain."],["Rip saw","That’s for cutting along the grain."],["Hacksaw","That’s for metal."],["Coping saw","That’s for curves."],"plank"],
    ["wood",1,"Rip Tide","{n} needs to cut along the grain. Which saw?",["Rip saw","Its teeth are made for cutting along the grain."],["Crosscut saw","That’s for across the grain."],["Hacksaw","That’s for metal."],["Coping saw","That’s for curves."],"plank"],
    ["wood",2,"Curly Cut","{n} needs to cut a curve in thin board. Which saw?",["Coping saw","Its thin blade turns round curves."],["Rip saw","That cuts straight along the grain."],["Crosscut saw","That cuts straight across the grain."],["Tenon saw","That cuts straight joints."],"plank"],
    ["wood",2,"Tailspin","Which joint is traditional for a strong drawer front?",["Dovetail","The tails lock in so the front can’t pull off."],["Butt joint","It’s weak on its own."],["Halving joint","That’s for crossing rails."],["Mitre","That’s for neat corners like frames."],"plank"],
    ["wood",2,"Frame Fiend","Which joint fixes a rail into a stile in a door frame?",["Mortise and tenon","The tenon fits tight in the mortise: strong and square."],["Mitre","That’s for corners like picture frames."],["Dovetail","That’s for drawers and boxes."],["Butt joint","It’s too weak on its own."],"plank"],
    ["wood",2,"Corner Cutter","Two pieces meet at 45° for a neat corner. What joint is it?",["Mitre","Two 45° cuts make a 90° corner."],["Halving","That’s half cut out of each piece."],["Dovetail","That has interlocking tails."],["Housing","That’s a slot across the grain."],"plank"],
    ["wood",2,"Door Guard","How many hinges does a standard fire door need?",["Three","Three hinges keep a fire door closed and in line."],["One","That wouldn’t hold it."],["Two","Fire doors need three."],["Five","Three is the standard."],"plank"],
    ["wood",3,"Shrinker","Timber shrinks most in which direction?",["Around the growth rings (tangentially)","Most shrinkage is along the rings, less across them and hardly any lengthways."],["Along its length","Timber hardly shrinks lengthways."],["Across the rings (radially)","It shrinks less that way than along the rings."],["It doesn’t shrink","Timber shrinks as it dries."],"plank"],
    ["wood",2,"Rot Rider","What does timber preservative protect against?",["Rot and insects","It stops fungi and woodworm attacking the timber."],["Fire","That’s a fire retardant."],["Shrinking","Preservative doesn’t stop shrinkage."],["Nails","It doesn’t affect fixings."],"plank"],
    ["wood",1,"Stud Dud","How will {n} check a stud is upright?",["Spirit level","Held against the stud, it shows if it’s plumb."],["Try square","That checks 90° corners."],["Tape measure","That checks lengths."],["Chalk line","That marks straight lines."],"plank"],
    ["wood",2,"Joist Jumper","What’s used to hang a joist off a beam or wall?",["Joist hanger","A galvanised steel hanger carries the joist’s end."],["Door hinge","That’s for doors."],["Shelf bracket","It isn’t strong enough."],["Glue","It won’t carry the load."],"plank"],

    /* ---------- On site ---------- */
    ["site",1,"Gap Rail","The scaffold has a missing guard rail. What will {n} do?",["Keep off and tell the supervisor","Only a competent scaffolder should put it right."],["Use it carefully","Falls from height kill. Keep off."],["Fix it themselves","Only a scaffolder should change a scaffold."],["Hold on to the frame","Keep off it."],"hazard"],
    ["site",1,"Heavy Bag","How will {n} lift a 25 kg bag of cement?",["Bend the knees, keep it close, back straight","Your legs do the lifting, not your back."],["Bend the back and pull","That’s how backs get injured."],["Twist while lifting","Twisting with a load injures your back."],["Snatch it up fast","Lift smoothly."],"hazard"],
    ["site",1,"Ladder Lean","What angle should a ladder be at?",["1 out for every 4 up","About 75°. It’s the safest angle."],["1 out for every 2 up","Too shallow: it can slide out."],["Straight up","It could tip backwards."],["Any angle if it’s tied","Tied or not, set it at 1 in 4."],"hazard"],
    ["site",2,"Near Miss","A brick drops and just misses {n}. What now?",["Report it","Near misses are reported so the cause is fixed before someone gets hurt."],["Keep quiet","Next time it might hit someone."],["Laugh it off","It needs reporting."],["Just tell a mate","Report it properly."],"hazard"],
    ["site",1,"Talky Box","What’s a toolbox talk?",["A short safety briefing","A quick talk about a hazard or task, usually before work."],["A tool shop","It’s a safety briefing."],["A lunch break","It’s a safety briefing."],["An exam","It’s a short talk."],"hazard"],
    ["site",2,"Riddor","What is RIDDOR about?",["Reporting injuries and dangerous incidents","Some injuries, diseases and dangerous occurrences must be reported to the HSE."],["Ladder safety","That’s the Work at Height Regulations."],["Noise levels","That’s the Control of Noise Regulations."],["Tax on site","It’s about reporting incidents."],"hazard"],
    ["site",2,"Step Sheet","What does a method statement tell {n}?",["How to do the job safely, step by step","It sets out the safe way to do the work."],["The price of the job","That’s the quote."],["Who’s on holiday","That’s not it."],["The site address only","It’s the safe way to do the job."],"hazard"],
    ["site",2,"Risk Riddler","What does a risk assessment do?",["Finds hazards and how to control them","It looks at what could go wrong and how to stop it."],["Lists the tools","That’s a tool list."],["Sets the wages","That’s not it."],["Replaces PPE","It decides what PPE is needed."],"hazard"],
    ["site",3,"Height Hierarchy","Under the Work at Height rules, what comes first?",["Avoid working at height if you can","Then prevent falls, then reduce what happens if someone falls."],["Wear a harness","A harness comes later in the order."],["Use a ladder","Ladders are for short, low-risk jobs."],["Put a net up","Nets come after preventing falls."],"hazard"],
    ["site",1,"Frayed Cable","A drill’s cable is damaged. What will {n} do?",["Don’t use it: label it and report it","A damaged cable can electrocute you."],["Tape it and carry on","Tape won’t make it safe."],["Use it carefully","It’s still dangerous."],["Leave it for the next person","Label it so nobody uses it."],"hazard"],
    ["site",1,"Voltage Vole","What voltage are power tools on UK sites usually?",["110 V","It cuts the risk of a fatal shock."],["230 V","That’s household mains."],["12 V","Too low for most site tools."],["400 V","That’s three-phase for big plant."],"hazard"],
    ["site",2,"New Starter","What’s a site induction for?",["The site’s rules, hazards and emergency plans","Every site is different. Know it before you start."],["Getting your wages","It’s about safety."],["Picking your tools","It’s about the site."],["A day off","It’s the start of your first day."],"hazard"],
    ["site",2,"Quiet Mate","A mate has seemed down and quiet for weeks. What will {n} do?",["Check in and point them to support","Asking if they’re OK can make a big difference."],["Ignore it","They might need help."],["Joke about it","That can make it worse."],["Tell everyone","Keep it private."],"cloud"],

    /* ---------- Maths ---------- */
    ["maths",1,"Price Tag","{n} needs 12 m of skirting at £4 a metre. What does it cost?",["£48","12 × 4 = 48."],["£16","That’s 12 + 4."],["£40","12 × 4 is 48."],["£52","12 × 4 is 48."],"calc"],
    ["maths",1,"Area 51","A wall is 5 m long and 2 m high. What’s its area?",["10 m²","5 × 2 = 10 m²."],["7 m²","That’s 5 + 2."],["14 m²","That’s the perimeter, 5 + 2 + 5 + 2."],["25 m²","That’s 5 × 5."],"calc"],
    ["maths",2,"Brick Count","About 60 bricks cover 1 m². How many for 10 m²?",["600","60 × 10 = 600."],["60","That’s for 1 m²."],["6000","That’s 60 × 100."],["160","60 × 10 is 600."],"calc"],
    ["maths",2,"Waste Not","Add 10% to 600 bricks for waste. How many?",["660","10% of 600 is 60. 600 + 60 = 660."],["610","10% of 600 is 60, not 10."],["606","10% of 600 is 60."],["700","That’s adding 100."],"calc"],
    ["maths",2,"Round the Room","What’s the perimeter of a 4 m by 3 m room?",["14 m","4 + 3 + 4 + 3 = 14 m."],["12 m","That’s the area in m²."],["7 m","That’s only two sides."],["24 m","That’s double the area."],"calc"],
    ["maths",2,"Metric Mix","How many millimetres is 1.5 m?",["1500 mm","1 m = 1000 mm."],["150 mm","That’s 15 cm."],["15 mm","Far too small."],["15000 mm","That’s 15 m."],"calc"],
    ["maths",2,"Square Up","To check a corner, sides of 3 m and 4 m make what diagonal when it’s square?",["5 m","3-4-5: the diagonal of a square corner."],["7 m","That’s 3 + 4."],["6 m","It’s 5 m."],["12 m","That’s 3 × 4."],"calc"],
    ["maths",3,"Slab Sum","A slab is 4 m × 2 m × 0.1 m deep. What’s its volume?",["0.8 m³","4 × 2 × 0.1 = 0.8."],["8 m³","That forgets the 0.1 m depth."],["80 m³","Much too big."],["0.08 m³","4 × 2 × 0.1 is 0.8."],"calc"],
    ["maths",1,"Half Measure","What’s half of 3 m?",["1.5 m","3 ÷ 2 = 1.5."],["1 m","3 ÷ 2 is 1.5."],["2 m","3 ÷ 2 is 1.5."],["6 m","That’s double."],"calc"],
    ["maths",3,"Crew Count","A job takes 3 people 4 days. How long for 6 people, working the same?",["2 days","Twice the people, half the time."],["8 days","More people means less time."],["1 day","Twice the people halves it: 2 days."],["3 days","Twice the people halves it."],"calc"],
    ["maths",2,"Round Robin","Round 2.46 m to one decimal place.",["2.5 m","The 6 rounds the 4 up to 5."],["2.4 m","6 is 5 or more, so round up."],["2 m","That’s to the nearest metre."],["3 m","That’s too far."],"calc"],
    ["maths",2,"Bag Ratio","A 1:4 mix uses a 25 kg bag of cement. How much sand?",["100 kg","4 × 25 = 100 kg."],["25 kg","That’s 1:1."],["125 kg","That’s cement and sand together."],["50 kg","That’s 1:2."],"calc"],

    /* ---------- English ---------- */
    ["english",1,"Spell Bug","Which is spelt correctly?",["Necessary","One c, two s."],["Neccessary","One c."],["Necesary","Two s."],["Neccesary","One c, two s."],"book"],
    ["english",1,"There There","Pick the right word: “Put the tools over ___.”",["there","There is a place."],["their","Their means it belongs to them."],["they’re","They’re means they are."],["thier","That isn’t a word."],"book"],
    ["english",1,"Big Letter","Which word always needs a capital letter?",["London","Names of places always start with a capital."],["brick","It only needs one at the start of a sentence."],["trowel","It only needs one at the start of a sentence."],["site","It only needs one at the start of a sentence."],"book"],
    ["english",2,"Polite Post","How will {n} start a message to the site manager?",["“Hi Sarah, I wanted to let you know…”","Polite and clear."],["“Yo”","Too casual for work."],["“OI!”","Rude."],["“Sarah!!!!”","Too many exclamation marks."],"book"],
    ["english",2,"Fact Checker","Which is a fact, not an opinion?",["The wall is 2 m high","It can be measured."],["It’s the best wall on site","That’s an opinion."],["It looks lovely","That’s an opinion."],["It should be taller","That’s an opinion."],"book"],
    ["english",2,"Were Wolf","Pick the right word: “The bricks ___ delivered today.”",["were","Bricks is plural, so were."],["was","Was is for one thing."],["is","It happened today: past tense."],["be","That doesn’t fit."],"book"],
    ["english",2,"Apostrophe Ape","Where is the apostrophe used correctly?",["The supervisor’s van","The van belongs to the supervisor."],["Brick’s for sale","Plurals don’t need apostrophes."],["Its’ raining","It’s = it is."],["Tool’s everywhere","Plurals don’t need apostrophes."],"book"],
    ["english",3,"Formal Phantom","Which is a more formal word for “get” in a report?",["Obtain","Formal and clear."],["Grab","Too casual."],["Nab","Slang."],["Snag","Slang."],"book"],
    ["english",2,"Purpose Puzzle","What’s the purpose of a method statement?",["To instruct","It tells people how to do the job."],["To entertain","It’s not a story."],["To persuade","It isn’t selling anything."],["To advertise","It’s instructions."],"book"],
    ["english",1,"Question Mark","Which mark ends: “Where is the ladder”?",["?","It’s a question."],[".","That’s for statements."],["!","That’s for strong feeling."],[",","That’s for a pause."],"book"],

    /* ---------- Equality, diversity and safeguarding ---------- */
    ["edi",1,"Mocker","A new apprentice is being mocked for their accent. What will {n} do?",["Say it’s not OK, and tell a supervisor if it carries on","Everyone deserves respect at work."],["Join in","That’s bullying."],["Ignore it","Saying nothing lets it carry on."],["Laugh along","That encourages it."],"cloud"],
    ["edi",2,"Fair Share","What does equality mean?",["Everyone gets fair chances","Nobody is treated worse because of who they are."],["Everyone is exactly the same","People are different. Equality is about fair treatment."],["Only some people get help","That isn’t equality."],["Whoever shouts loudest wins","That isn’t fair."],"cloud"],
    ["edi",2,"Step Stool","What does equity mean?",["Giving people what they need for a fair chance","Different people may need different support."],["Everyone gets exactly the same","That’s equality, not equity."],["Some people get nothing","That isn’t fair."],["Luck decides","It’s about fairness."],"cloud"],
    ["edi",2,"Protected","Which is a protected characteristic in the Equality Act 2010?",["Disability","Others include age, race, religion, sex and sexual orientation."],["Favourite football team","That isn’t protected by law."],["Van model","That isn’t protected."],["Shoe size","That isn’t protected."],"cloud"],
    ["edi",2,"Secret Keeper","An apprentice tells {n} someone is hurting them at home. What now?",["Tell the college’s safeguarding lead","Don’t promise to keep it secret. The safeguarding lead knows how to help."],["Keep it secret as promised","They could be in danger."],["Sort it out themselves","Leave it to people trained to help."],["Post about it","That breaks their privacy."],"cloud"],
    ["edi",1,"Bad Banter","Jokes aimed at someone’s religion are what?",["Harassment","It’s against the law and against site rules."],["Just a laugh","Not to the person it’s aimed at."],["Fine if they’re not there","It still isn’t OK."],["Team building","It pushes people out."],"cloud"],
    ["edi",2,"Prevent","What is the Prevent duty about?",["Protecting people from being drawn into extremism","Anyone worried should talk to the safeguarding lead."],["Preventing accidents","That’s health and safety."],["Preventing lateness","That’s not it."],["Preventing theft","That’s security."],"cloud"],
    ["edi",2,"Values","Which is one of the British values?",["Democracy and the rule of law","Plus individual liberty, and respect and tolerance."],["Always agreeing with the boss","That isn’t one of them."],["Everyone thinks the same","Tolerance means respecting differences."],["Winning at all costs","That isn’t one."],"cloud"],
    ["edi",1,"Upstairs Downstairs","A colleague uses a wheelchair and the canteen is upstairs. What’s best?",["Make a reasonable adjustment","For example, a break area on the ground floor."],["Nothing: it’s their problem","Employers have to make reasonable adjustments."],["Carry them up","Ask what they need, and find a proper solution."],["Tell them to eat outside","That leaves them out."],"cloud"],
    ["edi",1,"Left Out","Someone is always left out of the team at breaks. What will {n} do?",["Include them","A good team makes everyone welcome."],["Leave them to it","They may feel pushed out."],["Talk about them","That makes it worse."],["Tell them to toughen up","That isn’t kind or fair."],"cloud"]
  ],

  /* ---------- Bosses: steps in the order they happen ---------- */
  bosses:[
    {name:"Cable Inferno",art:"elec",intro:"The site cabin’s wiring is on fire!",key:[2,0,1,3,4],steps:[
      ["The site cabin’s wiring is on fire! What will {n} do first?",["Raise the alarm","Get everyone out and the fire service called."],["Grab tools from the cabin","Leave everything. Get out."],["Open all the windows","That feeds the fire with air."],["Hide under a desk","Get out and raise the alarm."]],
      ["It’s small and the exit is behind {n}. What next?",["Isolate the power, if it’s safe","With the power off, it’s much safer to tackle."],["Unplug things with wet hands","Never touch electrics with wet hands."],["Pour water on the socket","Water and electricity kill."],["Pull the cables out","You could be electrocuted."]],
      ["Which extinguisher?",["CO2 (black band)","Safe on electrical fires, and it leaves no mess."],["Water (red band)","Water conducts electricity."],["Foam (cream band)","Foam is water-based."],["Wet chemical (yellow band)","That’s for cooking oil."]],
      ["Where will {n} aim?",["At the base of the fire","Put out what’s burning, not the flames above it."],["At the top of the flames","You need to hit the fuel at the base."],["At the smoke","That won’t put it out."],["At the ceiling","Aim low, at the base."]],
      ["It’s out. What now?",["Report it and keep watching it","It could reignite, and it must be checked and reported."],["Get straight back to work","It could reignite."],["Say nothing","It must be reported."],["Switch the power back on","Only when it’s been checked by an electrician."]]
    ]},
    {name:"Timber Titan",art:"wood",intro:"Stacked timber by the hoarding is burning!",key:[2,0,1,3,4],steps:[
      ["Stacked timber by the hoarding is burning! What first?",["Raise the alarm","Everyone out, fire service called."],["Keep working","A fire spreads fast."],["Go and look closer","Keep back and raise the alarm."],["Move the stack","You could get burnt."]],
      ["Should {n} tackle it?",["Only if it’s small, they’re trained and have a way out","If not, get out and leave it to the fire service."],["Always: be a hero","Never put yourself at risk."],["Only if the boss is watching","It’s about whether it’s safe."],["Never report it","It must be reported."]],
      ["It’s small, and {n} is trained. Which extinguisher?",["Water (red band)","Water cools burning wood: class A."],["CO2 (black band)","CO2 doesn’t cool the wood, so it can flare up."],["Wet chemical (yellow band)","That’s for cooking oil."],["Fire blanket","Too small for a timber stack."]],
      ["How will {n} use it?",["Aim at the base and sweep side to side","It puts out the fuel, not just the flames."],["Spray at the flames","Flames aren’t the fuel."],["Empty it in one spot","Sweep across the base."],["Throw the extinguisher","Pull, aim, squeeze, sweep."]],
      ["It’s out. What now?",["Report it and keep an eye on it","It could flare up again."],["Walk off","It could flare up again."],["Hang the empty extinguisher back","It needs replacing, so report it."],["Cover it with more timber","That’s fuel."]]
    ]},
    {name:"Scaffold Shaker",art:"hazard",intro:"A scaffold board is missing, high above the yard.",key:[0,1,3,2,4],steps:[
      ["{n} spots a scaffold with a board missing. What first?",["Stay off it","Never use a scaffold that isn’t right."],["Step over the gap","One slip and it’s a fall."],["Use it quickly","Falls from height are the biggest killer on site."],["Jump the gap","Stay off it."]],
      ["Who needs to know?",["The supervisor","They’ll stop it being used and get it fixed."],["Nobody","Others could fall."],["Only a friend","Tell the supervisor."],["Post it online","Report it properly."]],
      ["What about other people?",["Warn them to keep off it","Stop anyone else using it."],["Let them find out","They could fall."],["Dare them to cross it","Never."],["Hide the ladder","Warn them and report it."]],
      ["Who can fix the scaffold?",["A competent scaffolder","Only a scaffolder should alter a scaffold."],["{n}","Only scaffolders alter scaffolds."],["Any labourer","It needs a scaffolder."],["The first person there","It needs a scaffolder."]],
      ["When can it be used again?",["When it’s been inspected and tagged safe","Check the scaffold tag before using it."],["Straight away","It needs inspecting first."],["When it looks OK","It needs a proper inspection."],["Tomorrow, whatever happens","Only once it’s passed inspection."]]
    ]},
    {name:"Dust Phantom",art:"dust",intro:"Old grey board behind the plaster could be asbestos.",key:[0,3,1,2,4],steps:[
      ["Drilling a wall, {n} uncovers old grey board that could be asbestos. What first?",["Stop work straight away","Asbestos fibres kill. Don’t disturb it any more."],["Carry on carefully","Every bit of drilling releases fibres."],["Break a bit off to check","That releases fibres."],["Sweep up the dust","Sweeping spreads the fibres."]],
      ["Then?",["Leave it alone and don’t disturb it","Leave it exactly as it is."],["Bag it up","Only licensed people remove it."],["Wet it and scrape it","Leave it for specialists."],["Vacuum it with a normal hoover","That spreads the fibres."]],
      ["Other people are nearby. What will {n} do?",["Keep them away from the area","Nobody should go near it."],["Let them carry on","They could breathe fibres in."],["Show them the find","Keep people away."],["Ask them to help clean up","Keep people away."]],
      ["Who does {n} tell?",["The supervisor","They’ll arrange for it to be tested."],["Nobody","Others could be exposed."],["Only the client","Tell the supervisor."],["Wait until the end of the week","Tell them now."]],
      ["Who can deal with it?",["A licensed asbestos specialist","Testing and removal need trained specialists."],["{n}, wearing a dust mask","A dust mask isn’t enough, and it needs a specialist."],["Any trade on site","It needs a specialist."],["Nobody: build over it","It must be dealt with properly."]]
    ]},
    {name:"Chip Pan Chomper",art:"oil",intro:"The canteen chip pan is on fire!",key:[2,0,1,3,4],steps:[
      ["The canteen chip pan is on fire! What first?",["Raise the alarm","Get people out and help coming."],["Carry the pan outside","Moving it spills burning oil."],["Throw water on it","A fireball."],["Film it","Raise the alarm."]],
      ["What next, if it’s safe?",["Turn off the heat","Take away the heat."],["Turn the heat up","That makes it worse."],["Put a lid on and stir","Don’t stir burning oil."],["Open the fridge","That doesn’t help."]],
      ["What will {n} use on it?",["Wet chemical (yellow band)","Made for cooking oil: class F."],["Water (red band)","Water on burning oil causes a fireball."],["CO2 (black band)","Can spread burning oil, and it can reignite."],["Foam (cream band)","Not made for cooking oil."]],
      ["After it’s out, what about the pan?",["Leave it to cool for a long time","Hot oil can reignite."],["Move it straight away","It’s still dangerous."],["Pour the oil down the drain","Never. And it’s still hot."],["Start cooking again","Let it cool and report it."]],
      ["Anything else?",["Report it","Every fire gets reported."],["Keep it quiet","It must be reported."],["Hang the extinguisher back","It needs replacing, so report it."],["Blame someone","Report it properly."]]
    ]},
    {name:"The Big Drop",art:"drop",intro:"A worker has fallen from a ladder!",key:[0,1,2,3,4],steps:[
      ["A worker has fallen from a ladder. What will {n} do first?",["Make sure the area is safe","Don’t become the next casualty."],["Run under the ladder","Something else could fall."],["Move them straight away","Moving them can make injuries worse."],["Walk off","Help, safely."]],
      ["Then?",["Call a first aider and 999","Get trained help fast."],["Give them a drink","Don’t give food or drink."],["Sit them up","Don’t move them."],["Tell them to shake it off","They need checking."]],
      ["While {n} waits for help?",["Stay with them and keep them still","Reassure them and don’t move them."],["Leave them alone","Stay with them."],["Get them to walk","Don’t move them."],["Take a photo","Stay with them."]],
      ["Who needs to know?",["The supervisor","They’ll deal with the reporting."],["Nobody","It must be reported."],["Only their family","The supervisor must know."],["Social media","Never."]],
      ["What happens after?",["It’s reported and investigated","So it doesn’t happen again. Serious injuries are reported under RIDDOR."],["Everyone forgets it","It must be looked into."],["Use the same ladder again","It needs checking."],["Blame the injured worker","Find the cause."]]
    ]}
  ]
};
