/* Site Showdown: the encounters (showdown.js plays them).
   Each encounter: [type, tier (1 to 3, harder as a run goes on), name, question, [right move, why], [wrong move, why],
   [wrong, why], [wrong, why], art]. {n} is the learner's first name. The right move is first here and shuffled in
   play. Every wrong move is a mistake someone could really make, and says why it's wrong.
   Types: fire, ppe, coshh, sign, plan, mix, brick, wood, site, maths, english, edi. Trade types are only used for the
   learner's trade (mix and brick: bricklaying; wood: carpentry and joinery); maths and English only if they're on.
   Facts are UK: extinguisher bands (BS EN 3, BS 7863), safety signs (BS EN ISO 7010), the Work at Height, Noise,
   Vibration, CoSHH and RIDDOR regulations, Approved Documents A and K, and the Equality Act 2010.
   Bosses: steps in the order they happen. Boss 1 has 1 step, boss 2 has 2 steps… up to 5. key gives which steps to
   use first, so a short boss still keeps the most important ones (in the order they happen); intro sets the scene. */
window.EVIA_SHOWDOWN={
  foes:[
    /* ---------- Fires ---------- */
    ["fire",1,"Timber Blaze","Offcuts of timber are burning in a pile. Which extinguisher is best?",["Water (red band)","Water cools burning wood, paper and fabric: class A."],["CO2 (black band)","CO2 smothers but doesn’t cool, so wood can reignite once the gas clears."],["Wet chemical (yellow band)","Wet chemical is made for cooking oil (class F). Use water on timber."],["Fire blanket","A blanket is for a small pan fire or someone’s clothes, not a pile of burning timber."],"wood"],
    ["fire",1,"Sparky Socket","A transformer on site is on fire. Which extinguisher?",["CO2 (black band)","CO2 is safe on electrical equipment and leaves nothing behind."],["Foam (cream band)","Standard foam is water-based and conducts electricity."],["Water (red band)","Water conducts electricity."],["Wet chemical (yellow band)","That’s for cooking oil fires, and it’s water-based."],"elec"],
    ["fire",2,"Petrol Flare","Petrol spilled by the mixer is burning. Which extinguisher?",["Foam (cream band)","Foam blankets burning liquids: class B."],["Water (red band)","Water spreads burning petrol."],["Wet chemical (yellow band)","That’s for cooking oil, not fuels."],["Fire blanket","A blanket can’t cover a spreading spill."],"liquid"],
    ["fire",2,"Pan Flame","A pan of cooking oil is on fire in the site canteen. Which extinguisher?",["Wet chemical (yellow band)","It cools the oil and forms a seal: class F."],["Foam, sprayed gently (cream band)","Foam isn’t made for very hot cooking oil."],["CO2, from a safe distance (black band)","The blast can spread burning oil, and it can reignite as the gas clears."],["Water mist (red band)","Water on burning oil causes a fireball."],"oil"],
    ["fire",2,"Gas Jet","Gas leaking from a bottle has caught light. What first?",["Shut the valve if you can reach it","Take away the fuel first. A gas flame put out while gas still leaks can explode."],["Put the flame out with dry powder","Put it out while gas still flows and the gas builds up. Stop the fuel first."],["Cool the bottle down with CO2","Cooling won’t stop the leak. Shut off the supply if it’s safe."],["Lay the bottle down on its side","Never move a burning cylinder."],"gas"],
    ["fire",3,"Swarf Spark","Metal swarf has caught fire. Which extinguisher?",["Class D powder","Burning metals need a special powder."],["Standard ABC powder","ABC powder isn’t rated for burning metals."],["CO2 (black band)","CO2 won’t put out burning metal."],["Water mist","Water on burning metal can react violently."],"metal"],
    ["fire",1,"Smoke Sneak","{n} sees smoke coming from under a store room door. What first?",["Raise the alarm","Alarm first, so everyone gets out and the fire service is called."],["Feel the door, then go in with an extinguisher","Opening the door can feed the fire. Raise the alarm first."],["Find the supervisor and ask what to do","Don’t lose time. Raise the alarm yourself."],["Prop the door open to let the smoke out","That feeds the fire with air."],"wood"],
    ["fire",2,"Band of Blue","An extinguisher has a blue band. What’s inside?",["Dry powder","Blue is dry powder: multi-purpose, but it makes a mess and blocks vision indoors."],["CO2","CO2 is black."],["Foam","Foam is cream."],["Wet chemical","Wet chemical is yellow."],"wood"],
    ["fire",2,"Black Band","An extinguisher has a black band. What’s it best for?",["Electrical fires","Black is CO2."],["Wood and paper","That’s water: red."],["Petrol and diesel","That’s foam: cream."],["Cooking oil","That’s wet chemical: yellow."],"elec"],
    ["fire",3,"Cold Snap","Why must you hold a CO2 extinguisher by the handle, not the horn?",["It gets cold enough to burn skin","CO2 comes out at about −78 °C."],["It gets hot enough to burn skin","It gets very cold, not hot."],["It can conduct electricity","The horn is non-conductive. It’s about cold burns."],["Holding it weakens the spray","It’s about frost burns to your hand."],"elec"],
    ["fire",3,"Small Room","Why shouldn’t CO2 be used in a small, closed room with people in it?",["It displaces the air you breathe","CO2 can suffocate people in a confined space."],["It can explode in a small room","CO2 doesn’t explode."],["It leaves a toxic residue","CO2 leaves nothing behind."],["It only works in open air","It works indoors, but not in a confined space with people."],"elec"],
    ["fire",1,"Siren Wail","The fire alarm sounds. What will {n} do?",["Go straight to the assembly point","Leave by the nearest exit and get counted."],["Finish the course, then go","Every second counts. Go now."],["Go back to the cabin for their phone","Never go back for belongings."],["Wait to hear if it’s a drill","Treat every alarm as real."],"wood"],
    ["fire",2,"Fire Triangle","Covering a pan fire with a fire blanket removes which side of the fire triangle?",["Oxygen","It smothers the fire."],["Heat","That’s what water does, by cooling."],["Fuel","That’s what shutting off a gas valve does."],["All three","A blanket cuts off oxygen."],"oil"],
    ["fire",3,"PASS Master","Using an extinguisher, what’s the right order?",["Pull, aim, squeeze, sweep","Pull the pin, aim at the base, squeeze, sweep side to side."],["Aim, pull, sweep, squeeze","The pin comes out first."],["Pull, squeeze, aim, sweep","Aim before you squeeze, or you waste it."],["Squeeze, pull, aim, sweep","It won’t work until the pin is out."],"wood"],

    /* ---------- Hazards and PPE ---------- */
    ["ppe",1,"Dust Devil","{n} is cutting blocks with a disc cutter. Which mask?",["FFP3, face-fit tested","Silica dust needs FFP3, and a tight-fitting mask only works if it fits your face."],["FFP1 disposable","FFP1 filters far too little for silica dust."],["A cloth face covering","Cloth doesn’t filter fine dust."],["Any mask, if the cutter has water on it","Water suppression helps, but you still need FFP3."],"dust"],
    ["ppe",1,"Racket","The breaker is so loud {n} has to shout to be heard a metre away. What’s needed?",["Ear protection, the whole time","If you have to shout to be heard, it’s loud enough to damage your hearing."],["Only after an hour of noise","Damage starts straight away at that level."],["Headphones with music on","They aren’t hearing protection, and they add noise."],["None, once you’re used to it","Getting used to noise means your hearing is already being damaged."],"noise"],
    ["ppe",1,"The Dropper","Scaffolders are working above. What does {n} need?",["Hard hat, and keep out of the drop zone","Protect your head, and stay out of the area below work."],["Hard hat, and it’s fine to work underneath","Hard hats don’t stop everything. Stay out of the drop zone."],["A bump cap","Bump caps aren’t for falling objects."],["Nothing if they’re careful","Falling objects kill. Hard hat and exclusion zone."],"drop"],
    ["ppe",1,"Splash","{n} is mixing lime. What protects their eyes?",["Sealed safety goggles","Lime burns eyes. Goggles seal against splashes."],["Safety glasses","Glasses leave gaps round the sides for splashes."],["A visor on its own","A visor alone can let splashes in underneath. Goggles seal."],["Prescription glasses","They aren’t rated for splashes or impact."],"splash"],
    ["ppe",1,"Nail Spike","Loose boards with nails are everywhere. What boots?",["Toecap and midsole (S3 or S1P)","A midsole stops nails going through."],["Toecap only (S1)","S1 has no midsole. Nails go through."],["Rigger boots with no toecap","They don’t protect toes or soles."],["Wellies","Standard wellies have no toecap or midsole."],"nail"],
    ["ppe",1,"Reverser","A dumper is reversing nearby. What’s most important for {n}?",["Stay clear and get the driver’s eye","Hi-vis helps, but getting out of the way is what keeps you safe."],["Walk behind it in your hi-vis","Drivers can’t see directly behind. Stay clear."],["Wave at the driver to stop","Only a trained banksman directs plant."],["Walk past it quickly","Wait until it’s stopped or clear."],"plant"],
    ["ppe",2,"Cement Burn","{n} is handling wet mortar all day. Which gloves?",["Nitrile-coated gloves","Cement causes burns and dermatitis. Keep it off your skin."],["Cloth rigger gloves","Wet cement soaks through and is held against the skin."],["Latex disposables","They tear easily on site."],["Leather gauntlets","Leather soaks up wet cement."],"splash"],
    ["ppe",2,"Knee Grinder","{n} is laying blocks at low level for hours. What helps most?",["Knee pads, changing position","Kneeling for hours damages knees."],["A dust sheet folded to kneel on","It gives little protection and slips."],["A board to kneel on, no pads","That makes it worse."],["Stretch well after work","It helps, but pads protect during the work."],"nail"],
    ["ppe",2,"Scorcher","A hot summer day on an open roof. What will {n} do?",["Cover up, sun cream, water","Sunburn and heat stroke are real risks."],["Top off to keep cool","Bare skin burns and raises skin cancer risk."],["Energy drinks to keep going","Caffeine and sugar don’t hydrate you. Water does."],["One long break at lunch","Short breaks in the shade often are better."],"sun"],
    ["ppe",2,"Buzz Hands","What cuts {n}’s risk of hand-arm vibration syndrome?",["Less time on it, low-vibe tools","Exposure time is what does the damage."],["Grip the tool tighter","A tight grip passes more vibration into your hands."],["Anti-vibration gloves only","They do very little on their own."],["Full power to finish sooner","Less time is better, but full throttle often means more vibration."],"noise"],
    ["ppe",3,"Last Line","In the hierarchy of control, what comes first?",["Eliminate the hazard","Then substitute, then engineering controls, then admin, then PPE."],["Wear the right PPE","PPE is the last line of defence."],["Put up warning signs","Signs are an admin control, low down the list."],["Train everyone","Training is an admin control."],"dust"],
    ["ppe",3,"Decibel","At what daily noise level must hearing protection be worn?",["85 dB(A)","The upper action value: protection is a must."],["80 dB(A)","At 80 it must be offered, not a must."],["70 dB(A)","Below the action values."],["100 dB(A)","Much too high: damage starts well before."],"noise"],
    ["ppe",3,"Clean Shave","Why must {n} be clean-shaven for a face-fit tested mask?",["Stubble breaks the seal","A tight-fitting mask only works if it seals."],["It’s a site dress code","It’s about the mask sealing."],["Masks irritate stubble","It’s about the seal, not comfort."],["It isn’t needed for FFP3","It matters for every tight-fitting mask."],"dust"],

    /* ---------- Substances (CoSHH) ---------- */
    ["coshh",1,"The Acronym","What does CoSHH stand for?",["Control of Substances Hazardous to Health","The rules for working safely with harmful substances."],["Control of Site Health and Hygiene","Close, but no."],["Code of Safe Handling of Hazards","That’s not it."],["Construction Substances and Health Hazards","That’s not it."],"drum"],
    ["coshh",2,"Soaker","Wet mortar has soaked through {n}’s sleeve onto their arm. What now?",["Wash it off with clean water straight away","Cement burns worsen the longer it stays on."],["Wipe it off and carry on","It leaves cement behind, still burning."],["Wait until it dries, then brush it off","Drying cement keeps burning."],["Put barrier cream over it","Barrier cream goes on clean skin before work."],"drum"],
    ["coshh",2,"Mystery Tin","Where will {n} find the PPE and first aid for a new sealant?",["The safety data sheet","It sets out hazards, PPE and first aid."],["The product’s price label","That won’t say how to use it safely."],["The toolbox talk from last month","It may not cover this product."],["The delivery note","It lists what was delivered, not how to use it safely."],"drum"],
    ["coshh",2,"Silica Cloud","Which activity makes the most silica dust?",["Dry-cutting concrete blocks","Dry cutting throws out clouds of fine silica dust."],["Laying blocks with fresh mortar","Wet mortar makes little dust."],["Painting a wall","Paint isn’t a silica source."],["Fitting insulation boards","Not a silica source."],"drum"],
    ["coshh",3,"Brick Acid","{n} is cleaning brickwork with brick acid. What first?",["Pre-wet the brickwork","Wetting first stops acid soaking in and staining."],["Apply it neat to dry bricks","That can burn and stain the bricks."],["Mix it stronger for a better clean","Stronger damages bricks and mortar."],["Scrub it in with a wire brush","Wire brushes scratch the face and leave rust stains."],"drum"],
    ["coshh",1,"Red Diamond","A tin has a red diamond with a flame in it. What does it mean?",["Flammable","The picture inside the red diamond shows the hazard."],["Keep hot","It warns it can catch fire."],["Harmful to the environment","That’s a tree and a fish."],["Explosive","That’s an exploding bomb picture."],"drum"],
    ["coshh",3,"Order Please","Under CoSHH, what’s the first thing to consider for a harmful product?",["Could a safer product replace it?","Remove or substitute before relying on PPE."],["Which gloves and goggles to buy?","PPE comes last."],["Where should it be stored?","Storage matters, but substitution comes first."],["How should spills be cleaned up?","That comes later."],"drum"],

    /* ---------- Safety signs (BS EN ISO 7010) ---------- */
    ["sign",1,"Blue Helmet","What does this sign mean?",["Hard hats must be worn","A blue circle is an instruction you must follow."],["Hard hats are recommended","Blue means must, not should."],["Caution: head injuries","A warning would be a yellow triangle."],["Hard hat store","Blue circles are instructions."],"hardhat"],
    ["sign",1,"No Smoke","What does this sign mean?",["No smoking","A red circle with a line means don’t."],["Smoking area","It’s a ban."],["Warning: fumes","A warning would be yellow."],["No naked flames only","It shows a cigarette, so no smoking."],"smoke"],
    ["sign",1,"Zap","What does this sign mean?",["Warning: electricity","Yellow triangles warn of a hazard."],["Electrical isolation point","It’s a warning, not a location."],["Switch off before starting","A must-do would be blue."],["High voltage: no entry","No entry would be a prohibition sign."],"bolt"],
    ["sign",1,"Green Cross","What does this sign mean?",["First aid","Green shows safe conditions."],["Emergency exit","Exits show a running figure."],["Red Cross station","It’s the first aid sign."],["Crossroads","It’s the first aid sign."],"cross"],
    ["sign",1,"Red Box","What does this sign mean?",["Fire extinguisher here","Red squares show firefighting equipment."],["Fire risk","A fire risk warning would be yellow."],["Fire alarm call point","That shows a different picture."],["Don’t use in a fire","It shows where the extinguisher is."],"ext"],
    ["sign",2,"Blue Ears","What does this sign mean?",["Ear protection must be worn","Blue circle: you must."],["Warning: loud noise area","A warning would be yellow."],["Quiet zone: no machines","It means wear ear protection."],["Headphones allowed here","It means wear ear protection."],"ears"],
    ["sign",2,"Blue Goggles","What does this sign mean?",["Eye protection must be worn","Blue circle: you must."],["Warning: flying debris","A warning would be yellow."],["Eye wash station","That’s a green sign."],["Welding area","That would show a mask or a warning."],"goggles"],
    ["sign",2,"Yellow Triangle","What kind of sign is a yellow triangle?",["Warning","It warns of a hazard."],["Mandatory","That’s a blue circle."],["Prohibition","That’s a red circle with a line."],["Safe condition","That’s green."],"warn"],
    ["sign",2,"Blue Circle","What kind of sign is a blue circle?",["Mandatory: you must","Blue circles are instructions."],["Information only","It’s an instruction."],["Warning","That’s a yellow triangle."],["Prohibition","That’s red with a line."],"must"],
    ["sign",2,"Red Line","What kind of sign is a red circle with a line?",["Prohibition","It bans something."],["Fire equipment","That’s a red square."],["Warning","That’s yellow."],["Mandatory","That’s blue."],"smoke"],
    ["sign",2,"Green Square","What kind of sign is a green square?",["Safe condition","First aid, exits, eye wash."],["Mandatory","That’s blue."],["Environmental","It shows safe conditions."],["Fire equipment","That’s red."],"cross"],

    /* ---------- Plans and scales ---------- */
    ["plan",1,"Scale Snake","On a 1:50 drawing, what’s 1 mm on paper on site?",["50 mm","Everything is 50 times bigger for real."],["5 mm","That would be 1:5."],["500 mm","That would be 1:500."],["0.5 m","That’s 500 mm: 1:500."],"plan"],
    ["plan",2,"Long Wall","At 1:50, a wall is 84 mm on the plan. How long is it?",["4.2 m","84 × 50 = 4200 mm."],["42 m","That’s 84 × 500."],["0.42 m","That’s 84 × 5."],["4.02 m","84 × 50 is 4200 mm."],"plan"],
    ["plan",2,"Hundred Scale","At 1:100, a wall is 47 mm on the plan. How long is it?",["4.7 m","47 × 100 = 4700 mm."],["47 m","That’s 47 × 1000."],["0.47 m","That’s 47 × 10."],["470 mm","That’s 47 × 10."],"plan"],
    ["plan",2,"Twenty Scale","At 1:20, a lintel is 90 mm on the drawing. How long is it?",["1.8 m","90 × 20 = 1800 mm."],["18 m","That’s 90 × 200."],["0.9 m","That’s 90 × 10."],["1.08 m","90 × 20 is 1800 mm."],"plan"],
    ["plan",1,"Bird’s Eye","Which drawing shows the building from above?",["Plan","A plan looks down."],["Elevation","That’s a face from the side."],["Section","That’s a slice through."],["Isometric","That’s a 3D view."],"plan"],
    ["plan",2,"Face Off","Which drawing shows the outside face of a wall?",["Elevation","Elevations show the faces."],["Section","That’s a slice through."],["Floor plan","That’s from above."],["Detail","That’s a close-up."],"plan"],
    ["plan",2,"The Slicer","Which drawing shows the layers of a cavity wall best?",["Section","A cut through shows each layer."],["Elevation","That shows the face only."],["Site plan","That shows the site."],["Location plan","That shows where the site is."],"plan"],
    ["plan",3,"Paper Wall","A 6.3 m wall at 1:50. How long on paper?",["126 mm","6300 ÷ 50 = 126."],["12.6 mm","That’s ÷ 500."],["315 mm","That’s ÷ 20."],["63 mm","That’s ÷ 100."],"plan"],
    ["plan",1,"Tiny Tray","Which scale best shows a cavity tray detail?",["1:5","Small ratios show details large."],["1:100","Too small for a detail."],["1:1250","That’s for location plans."],["1:50","Fine for plans, too small for details."],"plan"],
    ["plan",3,"Scale Swap","A wall is 60 mm long at 1:100. How long would it be at 1:50?",["120 mm","Twice the scale, twice the length."],["30 mm","1:50 is bigger, not smaller."],["60 mm","It changes with the scale."],["600 mm","That’s ten times."],"plan"],

    /* ---------- Mortar mixes (bricklaying) ---------- */
    ["mix",1,"Gauge Goblin","The spec says 1:5. For 3 buckets of cement, how much sand?",["15 buckets","3 × 5 = 15."],["5 buckets","That’s for 1 bucket of cement."],["8 buckets","That’s 3 + 5."],["12 buckets","That’s 1:4."],"tub"],
    ["mix",2,"Lime Lurker","The spec says 1:1:6. How much lime for 2 buckets of cement?",["2 buckets","1 lime to 1 cement."],["1 bucket","Double it all for 2 buckets."],["6 buckets","That’s the sand for 1 bucket of cement."],["3 buckets","1:1 means the same as the cement."],"tub"],
    ["mix",2,"Sand Heap","The spec says 1:1:6. How much sand for 2 buckets of cement?",["12 buckets","6 × 2 = 12."],["6 buckets","That’s for 1 bucket of cement."],["8 buckets","6 × 2 is 12."],["14 buckets","That counts the lime too."],"tub"],
    ["mix",2,"Shovel Slop","Why gauge by the bucket rather than by the shovel?",["Every mix comes out the same","Shovelfuls vary."],["It’s quicker to load","It’s about consistency."],["It uses less cement","It uses the right amount."],["The mixer needs it","It’s about consistency."],"tub"],
    ["mix",1,"Mud Pie","What makes mortar easier to work without adding extra water?",["Plasticiser or lime","They make it workable. Extra water weakens it."],["More cement","That makes it stronger and stickier, not more workable."],["Washing-up liquid","It’s not approved, and it weakens mortar."],["Coarse sharp sand","Sharp sand makes it harsher."],"tub"],
    ["mix",2,"Stiff Stuff","The mortar on the board has started to go off. What now?",["Bin it and mix fresh","Re-wetting mortar that’s setting weakens it."],["Add water and knock it up","Retempered cement mortar is weak."],["Add plasticiser","That won’t undo the setting."],["Use it for the backing work","Weak is weak anywhere."],"tub"],
    ["mix",3,"Frost Bite","Frost is forecast tonight. What about today’s brickwork?",["Cover it with insulated sheets","Frost can freeze the water in fresh mortar."],["Cover it with a single polythene sheet","Polythene alone doesn’t insulate. Use insulated covers."],["Brush it down and leave it","It needs protecting."],["Add antifreeze to tomorrow’s mix","That doesn’t protect today’s work."],"tub"],
    ["mix",3,"Bubble Trouble","How does plasticiser make mortar easier to work?",["It traps tiny air bubbles","The bubbles let it spread."],["It makes it set faster","That’s an accelerator."],["It adds water to the mix","It traps air."],["It dissolves the sand","No."],"tub"],

    /* ---------- Bricklaying ---------- */
    ["brick",1,"Recess Rex","The spec wants recessed joints. Which tool?",["Chariot","It rakes joints back to a set depth."],["Half-round jointer","That gives a bucket handle joint."],["Pointing trowel","That’s for flush or weather-struck."],["Frenchman","That trims weather-struck joints."],"wall"],
    ["brick",1,"Weathered Walt","The spec wants weather-struck joints. Which tool?",["Pointing trowel","Angled so rain runs off."],["Chariot","That makes a recessed joint."],["Half-round jointer","That makes a bucket handle joint."],["Soft brush","It cleans, it doesn’t shape."],"wall"],
    ["brick",2,"Rain Runner","Which joint finish sheds rainwater best?",["Weather-struck","It slopes outwards so water runs off."],["Recessed","It leaves a ledge that holds water."],["Raked out","That’s a recessed finish."],["Flush and rough","Rough joints hold water."],"wall"],
    ["brick",1,"Leaning Tower","How will {n} check the wall is plumb?",["Spirit level held upright","That checks vertical."],["Line and pins","That keeps courses straight."],["Gauge rod","That checks course heights."],["Tape measure from the corner","That checks lengths."],"wall"],
    ["brick",1,"Wobbly Course","What keeps each course straight between corners?",["Line and pins, or line blocks","Tight between corners, the line keeps every brick in line."],["The spirit level on every brick","Too short for a long wall."],["A chalk line on the course below","Marks don’t keep the course straight."],["A tape along the face","A tape checks lengths."],"wall"],
    ["brick",2,"Gauge Ghost","4 courses of standard brickwork measure how high?",["300 mm","75 mm a course × 4."],["260 mm","That forgets the joints."],["280 mm","It’s 75 × 4."],["340 mm","Too high."],"wall"],
    ["brick",2,"Half Bat","Which tools cut a brick cleanly by hand?",["Club hammer and bolster","Score it, then a sharp tap."],["Brick hammer on its own","Rougher cut."],["The edge of the trowel","Rough, and it damages the trowel."],["Angle grinder, dry","Cuts, but makes silica dust."],"wall"],
    ["brick",2,"Half Lap","How much does stretcher bond overlap?",["Half a brick","Half bond spreads the load."],["Quarter of a brick","That’s quarter bond."],["Three-quarters","That’s not stretcher bond."],["It changes every course","It’s half, every course."],"wall"],
    ["brick",2,"English Eddie","Whole courses of headers alternating with whole courses of stretchers. Which bond?",["English","A course of headers, a course of stretchers."],["Flemish","Flemish mixes them in the same course."],["English garden wall","That has several stretcher courses to each header course."],["Stretcher","All stretchers."],"wall"],
    ["brick",2,"Flemish Fiona","Headers and stretchers alternating in the same course. Which bond?",["Flemish","Header, stretcher, header, stretcher."],["English","English has whole courses of each."],["Stack","Straight joints all the way."],["Header","All headers."],"wall"],
    ["brick",2,"Course Counter","A standard brick is 215 × 102.5 × 65 mm. What’s its length with a joint?",["225 mm","215 + 10."],["215 mm","You need the joint."],["230 mm","215 + 10 is 225."],["205 mm","215 + 10 is 225."],"wall"],
    ["brick",3,"Tie Tamer","Standard wall tie spacing in a cavity wall?",["900 mm across, 450 mm up","Closer at openings."],["450 mm across, 900 mm up","It’s the other way round."],["600 mm both ways","Not the standard."],["1200 mm across, 600 mm up","Too far apart."],"wall"],
    ["brick",3,"Reveal Rule","At an opening, how close should extra ties be up the reveal?",["Every 300 mm, within 225 mm of the opening","Extra ties stiffen the edge of the opening."],["Every 900 mm","That’s the normal spacing."],["No extra ties","Openings need extra ties."],["Every 450 mm, 600 mm from the opening","Closer than that."],"wall"],
    ["brick",2,"Drip Drop","What’s the drip on a wall tie for?",["Stops water crossing","It drips off in the cavity."],["Holds the insulation","That’s the clip."],["Adds extra strength","It’s about water."],["Sets the cavity width","It’s about water."],"wall"],
    ["brick",3,"Damp Riser","How high above finished ground level must the DPC be?",["At least 150 mm","So rain splashing off the ground doesn’t soak past it."],["At least 75 mm","Too low."],["At ground level","Rain splash would bridge it."],["At least 450 mm","Higher than needed."],"wall"],
    ["brick",3,"Weep Wisp","How far apart are weep holes above a cavity tray?",["900 mm max, two per opening","Water on the tray needs a way out."],["One per opening is enough","At least two."],["Every 225 mm along the tray","Closer than needed."],["None if there’s a DPC","The tray needs weep holes."],"wall"],
    ["brick",3,"Lintel Lee","Minimum end bearing for a standard lintel?",["150 mm each end","It spreads the load onto the wall."],["50 mm each end","Too little."],["100 mm at one end only","Both ends need bearing."],["300 mm each end","More than the standard minimum."],"wall"],
    ["brick",1,"Rain Cloud","Rain is coming and the brickwork is fresh. What will {n} do?",["Cover the top and face with sheeting","Rain washes out fresh joints and stains the face."],["Point it quickly before the rain","Rain will still wash it."],["Leave it: mortar needs water","Rain damages fresh work."],["Brush it with a dry brush","That won’t protect it."],"wall"],

    /* ---------- Carpentry and joinery ---------- */
    ["wood",1,"Square Bear","How will {n} check a frame is square?",["Measure both diagonals","Equal diagonals: square."],["Put a spirit level across it","That checks level."],["Measure all four sides","Equal sides can still be out of square."],["Use a sliding bevel","That copies angles."],"plank"],
    ["wood",1,"Cross Cutter","Cutting across the grain by hand. Which saw?",["Crosscut saw","Teeth made to cut across the grain."],["Rip saw","That’s along the grain."],["Coping saw","That’s for curves."],["Hacksaw","That’s for metal."],"plank"],
    ["wood",1,"Rip Tide","Cutting along the grain by hand. Which saw?",["Rip saw","Teeth made for along the grain."],["Crosscut saw","That’s across the grain."],["Tenon saw","That’s for fine joint cuts."],["Pad saw","That’s for small holes."],"plank"],
    ["wood",2,"Curly Cut","Cutting a tight curve in thin board. Which saw?",["Coping saw","Its thin blade turns tight curves."],["Tenon saw","That cuts straight."],["Panel saw","That cuts straight."],["Rip saw","That cuts straight."],"plank"],
    ["wood",2,"Tailspin","Which joint suits a drawer front best?",["Dovetail","Tails lock in so it can’t pull off."],["Butt","Too weak."],["Housing","That’s for shelves."],["Halving","That’s for crossing rails."],"plank"],
    ["wood",2,"Frame Fiend","Which joint connects a rail into a stile in a door?",["Mortise and tenon","Strong and square."],["Dowelled butt","Weaker for doors."],["Dovetail","That’s for drawers."],["Bridle","That’s an open corner joint."],"plank"],
    ["wood",2,"Corner Cutter","Two 45° cuts meeting in a neat corner. Which joint?",["Mitre","Two 45° cuts make 90°."],["Halving","That’s half cut from each."],["Scarf","That joins lengths end to end."],["Housing","That’s a slot."],"plank"],
    ["wood",2,"Door Guard","How many hinges does a standard fire door need?",["Three","Fire doors need three hinges."],["Two","Fire doors need three."],["Four","Three is the standard."],["Two, plus a closer","Three hinges, and a closer."],"plank"],
    ["wood",3,"Shrinker","Timber shrinks most in which direction?",["Tangentially (along the rings)","Most shrinkage is along the rings."],["Radially (across the rings)","Less than along the rings."],["Along its length","Hardly at all lengthways."],["Equally every way","It’s uneven."],"plank"],
    ["wood",2,"Rot Rider","What does timber preservative protect against?",["Fungal decay and insects","It stops rot and woodworm."],["Fire spreading across it","That’s a fire retardant."],["Shrinking as it dries","It doesn’t stop shrinkage."],["Warping and twisting","It doesn’t stop warping."],"plank"],
    ["wood",1,"Stud Dud","Checking a stud is upright. Which tool?",["Spirit level","It shows plumb."],["Try square","That checks 90°."],["Chalk line","That marks lines."],["Sliding bevel","That copies angles."],"plank"],
    ["wood",2,"Joist Jumper","What hangs a joist off a masonry wall?",["Joist hanger","A galvanised steel hanger carries the end."],["Angle bracket","Not made for joist loads."],["Truss clip","That’s for trusses."],["Frame fixing","That’s for window frames."],"plank"],
    ["wood",3,"Steep Steps","The maximum pitch for a private stair?",["42°","The limit for private stairs."],["45°","Too steep."],["38°","Allowed, but not the maximum."],["50°","Far too steep."],"plank"],
    ["wood",3,"Rise Right","The maximum rise of a step on a private stair?",["220 mm","The limit for private stairs."],["180 mm","Allowed, but not the maximum."],["250 mm","Too high."],["200 mm","Allowed, but not the maximum."],"plank"],
    ["wood",3,"2R+G","For a comfortable stair, what should twice the rise plus the going be?",["Between 550 and 700 mm","The 2R + G rule."],["Between 400 and 500 mm","Too small."],["Exactly 900 mm","It’s a range, 550–700."],["Anything under 800 mm","It’s 550–700."],"plank"],

    /* ---------- On site ---------- */
    ["site",1,"Gap Rail","A scaffold has a missing guard rail. What will {n} do?",["Keep off it and report it","Only a scaffolder can alter it."],["Use it but stay away from the edge","A fall still kills. Keep off."],["Put a scaffold board across the gap","Only a scaffolder should alter it."],["Clip on to the scaffold tube","Harnesses on scaffolds need a proper plan."],"hazard"],
    ["site",1,"Heavy Bag","{n} is lifting a 25 kg bag of cement. How?",["Knees bent, load close, back straight","Legs do the lifting."],["Legs straight, bend at the waist","That strains your back."],["A quick jerk to get it up","Lift smoothly."],["Arms out, away from your body","Close to the body is safer."],"hazard"],
    ["site",1,"Ladder Lean","What angle should a ladder be at?",["1 out for every 4 up","About 75°."],["1 out for every 2 up","Too shallow: it can slide."],["1 out for every 8 up","Too steep: it can tip back."],["Whatever feels steady","Use the 1 in 4 rule."],"hazard"],
    ["site",3,"Top Rung","How far above the landing should a ladder extend?",["About 1 m","So you have a handhold getting on and off."],["Level with the landing","No handhold."],["300 mm","Not enough."],["2 m","More than needed."],"hazard"],
    ["site",2,"Near Miss","A brick falls and just misses {n}. What now?",["Report it as a near miss","So the cause is fixed before someone’s hurt."],["Tell the scaffolders to be careful","It needs reporting properly."],["Only report it if it happens again","Report it now."],["Put a hard hat on and carry on","Report it."],"hazard"],
    ["site",1,"Talky Box","What’s a toolbox talk?",["A short safety briefing","Usually before work starts."],["A weekly tool inspection","That’s different."],["A new starter’s induction","Inductions are for new starters."],["A disciplinary meeting","It’s a briefing."],"hazard"],
    ["site",3,"Riddor","An injury keeps someone off work for more than 7 days. Under RIDDOR, when must it be reported?",["Within 15 days","Over-7-day injuries are reported within 15 days."],["Within 24 hours","That’s for deaths and specified injuries, by the quickest means."],["It doesn’t need reporting","Over-7-day injuries must be reported."],["At the end of the job","Within 15 days."],"hazard"],
    ["site",2,"Step Sheet","What does a method statement give {n}?",["The safe steps for the job","It turns the risk assessment into steps."],["The hazards and their ratings","That’s the risk assessment."],["The programme of works","That’s the schedule."],["The price for the job","That’s the quote."],"hazard"],
    ["site",2,"Risk Riddler","What’s a risk assessment for?",["Finding hazards and controls","What could go wrong and how to stop it."],["Deciding who’s to blame","It’s about prevention."],["Listing the job’s steps","That’s a method statement."],["Checking tools are safe","That’s an inspection."],"hazard"],
    ["site",3,"Height Hierarchy","Under the Work at Height rules, what comes first?",["Avoid it if you can","Then prevent falls, then limit the result of a fall."],["Use a harness","That limits a fall. Avoid and prevent first."],["Use a ladder","Ladders are for short, low-risk jobs."],["Put nets up","Nets limit a fall. Avoid and prevent first."],"hazard"],
    ["site",1,"Frayed Cable","A drill’s cable is nicked. What will {n} do?",["Stop, label it, report it","A damaged cable can kill."],["Tape it and carry on","Tape isn’t a proper repair."],["Use it on 110 V only","Still dangerous."],["Keep the cable off the floor","Still dangerous."],"hazard"],
    ["site",1,"Voltage Vole","What voltage are power tools on UK sites usually?",["110 V","It cuts the risk of a fatal shock."],["230 V","That’s household mains."],["415 V","That’s three-phase for big plant."],["24 V","Too low for most site tools."],"hazard"],
    ["site",3,"Scaff Check","How often must a scaffold be inspected?",["7 days, and after changes","And before first use."],["Every month","It’s every 7 days."],["Only when it’s put up","It’s every 7 days."],["Every day","7 days is the legal minimum, plus after changes."],"hazard"],
    ["site",3,"Toe Board","The minimum height of a toe board on a scaffold?",["150 mm","It stops things being kicked off."],["50 mm","Too low."],["300 mm","More than the minimum."],["It’s optional","Toe boards are needed."],"hazard"],
    ["site",3,"Rail Height","The minimum height of the top guard rail?",["950 mm","The legal minimum in construction."],["750 mm","Too low."],["1200 mm","More than the minimum."],["850 mm","Too low."],"hazard"],
    ["site",2,"New Starter","What’s a site induction for?",["Site rules, hazards, emergencies","Every site is different."],["Signing in and timesheets","It’s about safety."],["A test of your trade skills","It’s about the site."],["Getting your CSCS card","That’s separate."],"hazard"],
    ["site",2,"Quiet Mate","A mate has seemed down and quiet for weeks. What will {n} do?",["Ask how they are and point them to support","It can make a big difference."],["Give them space until they snap out of it","They might need help now."],["Tell the supervisor they’re slacking","Talk to them first."],["Tell the rest of the team","Keep it private."],"cloud"],
    ["site",3,"Old Board","Asbestos was banned in the UK in which year?",["1999","Buildings from before 2000 can still contain it."],["1985","Blue and brown were banned then. White was banned in 1999."],["2005","It was banned earlier."],["1970","It was used long after 1970."],"hazard"],

    /* ---------- Maths ---------- */
    ["maths",1,"Price Tag","12.5 m of skirting at £4.20 a metre. What’s the cost?",["£52.50","12.5 × 4.2 = 52.5."],["£50.40","That’s 12 × 4.2."],["£48.20","That’s off."],["£54.60","That’s 13 × 4.2."],"calc"],
    ["maths",1,"Area 51","A wall is 4.5 m long and 2.4 m high. What’s the area?",["10.8 m²","4.5 × 2.4."],["6.9 m²","That’s 4.5 + 2.4."],["13.8 m²","That’s the perimeter."],["9.6 m²","That’s 4 × 2.4."],"calc"],
    ["maths",2,"Brick Count","60 bricks per m². How many for 12.5 m²?",["750","60 × 12.5."],["720","That’s 60 × 12."],["600","That’s 60 × 10."],["7500","That’s 600 × 12.5."],"calc"],
    ["maths",2,"Waste Not","Add 5% for waste to 740 bricks.",["777","5% of 740 is 37."],["745","5% of 740 is 37, not 5."],["814","That’s 10%."],["770","5% of 740 is 37."],"calc"],
    ["maths",2,"Round the Room","The perimeter of a 4.2 m × 3.6 m room?",["15.6 m","4.2 + 3.6 + 4.2 + 3.6."],["7.8 m","That’s two sides."],["15.12 m","That’s the area."],["16.2 m","It’s 15.6."],"calc"],
    ["maths",2,"Metric Mix","How many millimetres is 2.35 m?",["2350 mm","1 m = 1000 mm."],["235 mm","That’s 23.5 cm."],["23 500 mm","That’s 23.5 m."],["2035 mm","2.35 m is 2350 mm."],"calc"],
    ["maths",2,"Square Up","Setting out a corner, sides of 6 m and 8 m. What diagonal makes it square?",["10 m","6-8-10 is 3-4-5 doubled."],["14 m","That’s 6 + 8."],["12 m","It’s 10."],["9 m","It’s 10."],"calc"],
    ["maths",3,"Slab Sum","A slab 4 m × 3 m × 150 mm deep. What volume of concrete?",["1.8 m³","4 × 3 × 0.15."],["18 m³","That uses 1.5 m depth."],["0.18 m³","That uses 15 mm depth."],["1.2 m³","That uses 100 mm depth."],"calc"],
    ["maths",1,"Half Measure","A 2.7 m board cut in half. How long is each piece (ignoring the saw cut)?",["1.35 m","2.7 ÷ 2."],["1.3 m","2.7 ÷ 2 is 1.35."],["1.4 m","2.7 ÷ 2 is 1.35."],["1.25 m","2.7 ÷ 2 is 1.35."],"calc"],
    ["maths",3,"Crew Count","3 bricklayers take 8 days. How long for 4, working the same?",["6 days","3 × 8 = 24 days of work, ÷ 4."],["10.7 days","More people take less time."],["7 days","24 ÷ 4 is 6."],["4 days","24 ÷ 4 is 6."],"calc"],
    ["maths",2,"Round Robin","Round 3.846 m to the nearest centimetre.",["3.85 m","The 6 rounds the 4 up."],["3.84 m","6 rounds up."],["3.8 m","That’s to the nearest 10 cm."],["3.9 m","That’s to the nearest 10 cm."],"calc"],
    ["maths",3,"Gable Gap","A gable triangle is 6 m wide and 2.5 m high. What’s its area?",["7.5 m²","Half base × height: ½ × 6 × 2.5."],["15 m²","That forgets the half."],["8.5 m²","That’s 6 + 2.5."],["3.75 m²","That halves twice."],"calc"],
    ["maths",3,"Bag Ratio","A 1:4 mix, cement in 25 kg bags. How many bags for 500 kg of sand?",["5 bags","500 ÷ 4 = 125 kg cement = 5 bags."],["20 bags","That’s 500 ÷ 25."],["4 bags","That’s 100 kg of cement."],["125 bags","That’s kilograms, not bags."],"calc"],

    /* ---------- English ---------- */
    ["english",1,"Spell Bug","Which is spelt correctly?",["Separate","One a in the middle: sep-a-rate."],["Seperate","A common mistake."],["Seprate","A letter is missing."],["Separete","The ending is -ate."],"book"],
    ["english",1,"There There","Pick the right word: “___ going to deliver the blocks at 8.”",["They’re","They’re = they are."],["Their","Their means belonging to them."],["There","There is a place."],["Theyre","It needs an apostrophe."],"book"],
    ["english",2,"Plain Speaking","Which sentence is clearest for a report?",["The top rung was cracked, so I took the ladder out of use.","Says what, and what was done."],["The ladder was a bit dodgy but I sorted it out for now.","Too vague for a report."],["There was an equipment issue, which has been actioned.","Too vague."],["Ladder broke again, someone needs to look at it!!","Not clear or professional."],"book"],
    ["english",2,"Polite Post","Best way to email the site manager about a late delivery?",["“The blocks haven’t come. Can you chase them?”","Clear and polite."],["“Where’s the blocks? Been waiting all morning”","Rude and unclear."],["“Nothing’s ever on time on this site.”","A moan, not a request."],["“URGENT – NO BLOCKS – SORT IT!!!”","Shouting and unclear."],"book"],
    ["english",2,"Fact Checker","Which is a fact, not an opinion?",["The wall is 2.1 m high","It can be measured."],["It’s the neatest wall on site","That’s an opinion."],["It was built too slowly","That’s an opinion."],["It’s a strong design","That’s an opinion."],"book"],
    ["english",2,"Were Wolf","Pick the right word: “Each of the bricks ___ checked.”",["was","Each is singular."],["were","Each takes a singular verb."],["are","Past tense, singular: was."],["have","That doesn’t fit."],"book"],
    ["english",2,"Apostrophe Ape","Which is correct?",["The workers’ cabin","One cabin belonging to several workers."],["The worker’s’ cabin","Too many apostrophes."],["The workers cabin’","The apostrophe goes after the s of workers."],["The workers’s cabin","Plural owner: just the apostrophe."],"book"],
    ["english",3,"Formal Phantom","Which is the most formal way to write it in a report?",["The materials were obtained from the supplier.","Formal and clear."],["We got the stuff off the supplier.","Too casual."],["The gear came in from the supplier.","Slang."],["Supplier sorted us out with materials.","Too casual."],"book"],
    ["english",2,"Purpose Puzzle","What’s the main purpose of a method statement?",["To instruct","It tells people how to do the job."],["To persuade","It isn’t selling anything."],["To describe the site","It’s about how to do the work."],["To entertain","It’s instructions."],"book"],
    ["english",1,"Comma Chameleon","Which sentence uses commas correctly?",["We need sand, cement, lime and water.","Commas separate items in a list."],["We need, sand cement, lime and water.","The first comma is in the wrong place."],["We need sand cement lime, and, water.","Too many commas in the wrong places."],["We, need sand, cement, lime, and water.","A comma after “we” breaks the sentence."],"book"],

    /* ---------- Equality, diversity and safeguarding ---------- */
    ["edi",1,"Mocker","A new apprentice is mocked for their accent every day. What will {n} do?",["Challenge it, and report it","Everyone deserves respect."],["Stay out of it: it’s banter","It’s bullying if it’s aimed at someone again and again."],["Tell them to toughen up","That puts the blame on them."],["Wait to see if they complain","Act now."],"cloud"],
    ["edi",2,"Fair Share","What does equality mean at work?",["Fair chances for everyone","Fair treatment for all."],["Everyone gets exactly the same","That’s sameness. Some people need different support."],["Extra help for some groups only","That isn’t the definition."],["Treat others as you’d like","Close, but it’s about fair chances for all."],"cloud"],
    ["edi",2,"Step Stool","What does equity mean?",["What each person needs to be fair","Different support for a fair outcome."],["Everyone gets exactly the same","That’s equality."],["Everyone earns the same","That isn’t it."],["Everyone’s treated the same","That’s equality."],"cloud"],
    ["edi",2,"Protected","Which is a protected characteristic in the Equality Act 2010?",["Pregnancy and maternity","There are 9, including age, disability, race, religion, sex and sexual orientation."],["Trade qualification","That isn’t protected."],["Postcode","That isn’t protected."],["Political party","That isn’t on the list."],"cloud"],
    ["edi",2,"Secret Keeper","An apprentice tells {n} someone is hurting them at home, and asks them not to tell. What now?",["Tell the safeguarding lead","The safeguarding lead knows how to help."],["Keep it secret as promised","They could be in danger."],["Confront the person yourself","That could make it worse."],["Ask mates to keep an eye out","Tell the safeguarding lead."],"cloud"],
    ["edi",1,"Bad Banter","A “joke” about someone’s religion upsets them. What is it?",["Harassment","The law judges it by how it affects the person."],["Fine if it was meant as a laugh","Intent doesn’t make it OK."],["Only a problem if a manager heard","It’s wrong either way."],["Free speech","Not at work, when it harasses someone."],"cloud"],
    ["edi",2,"Prevent","What is the Prevent duty about?",["Stopping radicalisation","Worries go to the safeguarding lead."],["Preventing accidents","That’s health and safety."],["Preventing bullying","That’s part of safeguarding, but Prevent is about radicalisation."],["Preventing fraud","That’s not it."],"cloud"],
    ["edi",2,"Values","Which is one of the British values?",["Mutual respect and tolerance","With democracy, the rule of law and individual liberty."],["Loyalty to your employer","That isn’t one."],["Hard work","Good, but not one of them."],["Patriotism","That isn’t one."],"cloud"],
    ["edi",1,"Upstairs Downstairs","A colleague uses a wheelchair and the canteen is upstairs. What’s right?",["A reasonable adjustment","Employers must make reasonable adjustments."],["Nothing, if it costs money","Reasonable adjustments are a legal duty."],["Bring food down for them","Ask what they need. It’s about access."],["Give them longer breaks","That doesn’t solve access."],"cloud"],
    ["edi",1,"Left Out","Someone is always left out of the team at breaks. What will {n} do?",["Invite them in","A good team includes everyone."],["Leave it: they might prefer it","Ask, and include them."],["Ask the supervisor to sort it","You can make the difference yourself first."],["Tell them to make more effort","Put the effort in yourself."],"cloud"]
  ],

  /* ---------- Bosses: steps in the order they happen ---------- */
  bosses:[
    {name:"Cable Inferno",art:"elec",intro:"The site cabin’s wiring is on fire!",key:[2,0,1,3,4],steps:[
      ["What will {n} do first?",["Raise the alarm","Everyone out, fire service called."],["Tackle it straight away","Alarm first."],["Find the supervisor","Raise the alarm yourself."],["Open the windows to clear smoke","That feeds the fire."]],
      ["It’s small and the exit is behind {n}. What next?",["Isolate the power, if it’s safe","With the power off it’s safer to tackle."],["Unplug the cables","You could be electrocuted."],["Throw water over the socket","Water conducts."],["Wait for it to burn out","It could spread."]],
      ["Which extinguisher?",["CO2 (black band)","Safe on electrics, no mess."],["Foam (cream band)","Water-based."],["Water (red band)","Conducts electricity."],["Wet chemical (yellow band)","For cooking oil."]],
      ["Where will {n} aim?",["At the base of the fire","Put out the fuel."],["At the top of the flames","Aim at the base."],["Into the smoke","Aim at the base."],["Across the ceiling","Aim at the base."]],
      ["It’s out. What now?",["Report it and keep watching it","It could reignite."],["Switch the power back on to check","Only after an electrician’s checked it."],["Hang the extinguisher back","A used extinguisher must be replaced."],["Get back to work","It could reignite. Report it."]]
    ]},
    {name:"Timber Titan",art:"wood",intro:"Stacked timber by the hoarding is burning!",key:[2,0,1,3,4],steps:[
      ["What first?",["Raise the alarm","Everyone out, fire service called."],["Move the timber away","You could get burnt."],["Grab the nearest extinguisher","Alarm first."],["Call the site manager","Raise the alarm first."]],
      ["Should {n} tackle it?",["Only if it’s small, they’re trained and have a way out","Otherwise get out."],["Yes, always try first","Only if it’s safe."],["Only if the fire service is late","Only if it’s safe."],["Yes, if they have PPE on","PPE doesn’t make fighting fire safe."]],
      ["It’s small, and {n} is trained. Which extinguisher is best?",["Water (red band)","Class A: wood."],["CO2 (black band)","It won’t cool the wood."],["Wet chemical (yellow band)","For cooking oil."],["Dry powder (blue band)","It works, but water cools and stops it reigniting."]],
      ["How will {n} use it?",["Aim at the base, sweep side to side","It puts out the fuel."],["Aim at the flames","Aim at the base."],["One long burst at the middle","Sweep across the base."],["Short bursts from the far side","Stay with your exit behind you."]],
      ["It’s out. What now?",["Report it and keep an eye on it","It could flare up."],["Restack the timber","It could still be smouldering."],["Hang the extinguisher back","Report it so it’s replaced."],["Hose it down and leave it","Report it."]]
    ]},
    {name:"Scaffold Shaker",art:"hazard",intro:"A scaffold board is missing, high above the yard.",key:[0,1,3,2,4],steps:[
      ["What will {n} do first?",["Stay off it","Never use an unsafe scaffold."],["Step over the gap carefully","One slip is a fall."],["Use it if you clip on","Stay off it."],["Put a spare board in","Only scaffolders alter scaffolds."]],
      ["Who needs to know?",["The supervisor","They’ll stop it being used."],["The scaffolders, at the end of the day","Tell the supervisor now."],["Nobody if they stay off it","Others could fall."],["The client","Tell the supervisor."]],
      ["What about other people?",["Warn them and keep them off","Stop anyone else using it."],["Let them decide for themselves","Warn them."],["Tape the ladder up yourself","Warn them and report it."],["Nothing, the supervisor will sort it","Warn them now."]],
      ["Who can fix the scaffold?",["A competent scaffolder","Only scaffolders alter scaffolds."],["The site manager","It needs a scaffolder."],["{n}, with the right tools","It needs a scaffolder."],["Any trade on site","It needs a scaffolder."]],
      ["When can it be used again?",["When it’s inspected and tagged safe","Check the tag."],["Once the board is back","It needs inspecting."],["The next day","Only after inspection."],["When the supervisor says so verbally","It needs a proper inspection and tag."]]
    ]},
    {name:"Dust Phantom",art:"dust",intro:"Old grey board behind the plaster could be asbestos.",key:[0,3,1,2,4],steps:[
      ["What first?",["Stop work straight away","Don’t disturb it."],["Wet it and carry on carefully","Stop work."],["Break off a bit to check","That releases fibres."],["Finish the hole you’re drilling","Stop now."]],
      ["Then?",["Leave it alone","Don’t disturb it."],["Bag the loose bits","Only licensed people remove it."],["Sweep up the dust","Sweeping spreads fibres."],["Vacuum it up","A normal vacuum spreads fibres."]],
      ["Other people are nearby. What will {n} do?",["Keep them out of the area","Nobody should go near it."],["Let them carry on","They could breathe fibres."],["Tell them to wear dust masks","Keep them away."],["Ask them to help check it","Keep them away."]],
      ["Who does {n} tell?",["The supervisor, straight away","They arrange testing."],["The asbestos register, by filling it in","Tell the supervisor."],["The client, next time they visit","Tell the supervisor now."],["Nobody unless it’s confirmed","Tell them now."]],
      ["Who deals with it?",["A licensed asbestos specialist","Testing and removal need specialists."],["{n}, with an FFP3 mask","It needs a specialist."],["Any trained labourer","It needs a licensed specialist."],["Nobody: plaster over it","It must be dealt with."]]
    ]},
    {name:"Chip Pan Chomper",art:"oil",intro:"The canteen chip pan is on fire!",key:[2,0,1,3,4],steps:[
      ["What first?",["Raise the alarm","People out, help coming."],["Carry the pan outside","Spills burning oil."],["Put a wet tea towel over it","It can make it flare up."],["Put the lid on and carry it","Don’t move it."]],
      ["If it’s safe, what next?",["Turn off the heat","Take away the heat."],["Pour salt on it","Not reliable."],["Stir it to cool it","Never."],["Move it off the hob","Don’t move it."]],
      ["Which extinguisher?",["Wet chemical (yellow band)","Class F."],["CO2 (black band)","Can spread oil and reignite."],["Foam (cream band)","Not for cooking oil."],["Water (red band)","Fireball."]],
      ["After it’s out, what about the pan?",["Leave it to cool fully","Hot oil can reignite."],["Pour the oil into the sink","Never, and it’s still hot."],["Move it outside straight away","It’s still dangerous."],["Put it in the fridge","No."]],
      ["Anything else?",["Report it","Every fire is reported."],["Hang the extinguisher back","It must be replaced."],["Keep it quiet if there’s no damage","Report it."],["Start cooking again","Report it and let it cool."]]
    ]},
    {name:"The Big Drop",art:"drop",intro:"A worker has fallen from a ladder!",key:[0,1,2,3,4],steps:[
      ["What will {n} do first?",["Make sure the area is safe","Don’t become the next casualty."],["Run straight to them","Check for danger first."],["Sit them up","Don’t move them."],["Move the ladder away","Check it’s safe first."]],
      ["Then?",["Call a first aider and 999","Get trained help fast."],["Give them water","Don’t give food or drink."],["Help them walk it off","Don’t move them."],["Wait to see if they feel better","Get help now."]],
      ["While waiting?",["Stay with them, keep them still and warm","Reassure them."],["Lift their legs up","Don’t move them."],["Take their hard hat off","Don’t move their head."],["Leave them to get help","Stay with them if someone else calls."]],
      ["Who needs to know?",["The supervisor","They handle the reporting."],["Only their family","The supervisor must know."],["The ladder’s owner","Tell the supervisor."],["Nobody if they seem OK","It must be reported."]],
      ["What happens after?",["It’s investigated and reported under RIDDOR if needed","So it doesn’t happen again."],["The ladder is put back in use","It needs checking."],["It’s forgotten if they’re OK","It must be looked into."],["The injured worker is blamed","Find the cause."]]
    ]}
  ]
};
