/* Evia7 discussion guide: for each professional discussion question in test-banks.js (same course key, same order),
   a model answer to read (stage 1) and one prompt per key area (stage 2). Stage 3 is the question on its own.
   window.EVIA_EPA_GUIDE = {advice:[[title,text]], bricklaying:[{model,prompts}], siteCarpentry:[…], benchJoinery:[…]} */
window.EVIA_EPA_GUIDE={
  advice:[
    ["Answer in order","Talk it through like the job: prepare, do it, check it, finish off. A clear order shows you really know the work."],
    ["Use your own jobs","Say “On a job last month I…”. Real examples from your portfolio are worth more than general answers."],
    ["Say why, not just what","“I checked the level every few courses, because errors grow as the wall goes up.” The reason shows understanding."],
    ["Always mention safety and quality","PPE, safe use of tools, and how you checked your work against the drawings and tolerances come up in almost every question."],
    ["Use the right words","Name the tools, materials and terms: gauge, datum, bond, mortice, trimmer. It shows the assessor you know the trade."],
    ["It’s fine to pause","Take a breath before you answer. You can ask the assessor to repeat or explain the question."]
  ],
  bricklaying:[
    {model:"First I’d read the drawings and the specification, checking the plan, section and any details so I know the bond, the joint finish and the materials. I’d check the dimensions and set out from the datum, marking the corners and openings. Before starting I’d check my tools and equipment and wear the right PPE: boots, hard hat, gloves and eye protection when cutting. I’d make sure the materials are right and mix the mortar to the specified ratio of cement and sand, keeping the mix consistent. Then I’d build the corners first, run a line between them and keep every course to line, level and gauge, checking plumb as I go. At the end I’d check the bond, the joint finish and the quality of the face against the drawings.",
      prompts:["Which drawings and information would you check first?","How would you set out the dimensions?","What tools and PPE would you need?","How would you prepare the materials and mortar?","How would you keep it to line and level, and check the finish?"]},
    {model:"I’d start by reading the drawings and checking the dimensions, so I know exactly where the wall goes and how long it is. I’d find the datum or the building line and work from that as my starting point. Then I’d measure and mark out the wall, using a tape and a chalk line, and check that the corners are square with the 3-4-5 method or by measuring the diagonals. I’d dry-bond the first course to check the bond works out and avoid small cuts. Before laying anything I’d check all the final measurements again against the drawing, because a mistake in setting out carries all the way up the wall.",
      prompts:["What would you check on the drawings?","Where would you take your starting point from?","How would you measure and mark out the wall?","How would you check the corners and the bond?","What final checks would you do before laying?"]},
    {model:"First I’d check the mortar consistency: it should be workable, hold on the trowel and not be too wet or too stiff. I’d build the corners first to the right bond and check each course against the gauge rod so the courses are 75 mm. Then I’d run a line between the corners and lay to it, keeping the work to line and level, and checking plumb with the spirit level. I’d fill the joints fully and finish them to the specified joint, at the right time, so the finish is even. As the wall rises I’d keep doing quality checks for level, plumb, gauge and straightness, and clean off any mortar on the face.",
      prompts:["How would you check the mortar is right?","How would you keep the bond and gauge correct?","How would you keep the wall to line and level?","How and when would you finish the joints?","What quality checks would you make as it rises?"]},
    {model:"I’d stop and find the error first, using the spirit level, the line and the gauge rod to see whether it’s out of level, out of plumb or off the line, and how far. If it’s small I’d correct it on the next courses; if it’s out of tolerance I’d take the work down safely while the mortar is still green and relay it. I’d reset the line and check the level before carrying on, and make sure the bond and alignment still match the rest of the wall. I’d check back against the drawings and specification for the tolerances, tell my supervisor, and to stop it happening again I’d check more often as I build.",
      prompts:["How would you find the error?","Which checks would you use for line and level?","How would you correct it safely?","How would you keep the bond and alignment right?","What do the drawings and specification tell you?"]},
    {model:"I’d do a final inspection of the whole wall against the drawings. I’d check it’s to line, level and plumb, and that the joints are full, even and finished to the specification. I’d look for any defects like chipped bricks, mortar smudges or unfilled perps and put them right or report them. Then I’d clean my tools and store the tools and materials safely, cover any leftover bags and protect the new brickwork from rain or frost. Finally I’d do my housekeeping: clear away offcuts and waste into the right skip and leave the work area tidy and safe for the next trade.",
      prompts:["What would your final inspection cover?","How would you check the line and joints?","What defects would you look for and what would you do?","What would you do with tools and materials?","How would you leave the work area?"]}
  ],
  siteCarpentry:[
    {model:"I’d start with the drawings and specification to get the frame size, the timber, the joints and how it’s fixed. I’d check the dimensions of the opening on site and set out the frame, marking the head, jambs and joints. I’d pick the right tools and wear PPE: safety glasses and dust protection when cutting, and ear protection with power tools. Then I’d cut and assemble the frame, checking it’s square by measuring the diagonals. To install it I’d fix it in the opening with packers, and check it’s plumb, level and square, with even reveals, before the final fixings go in.",
      prompts:["What would you check on the drawings and specification?","How would you check the dimensions and set out?","Which tools and PPE would you use?","How would you cut and assemble the frame?","How would you install it and check it?"]},
    {model:"I’d read the drawings and details for the joist size, spacing, span and the direction they run. I’d set out the joists on the wall plate or hangers at the right centres, usually 400 mm, marking them all from one end. I’d check the timber is the right grade and size and choose the right fixings, like joist hangers with the correct nails in every hole. I’d make sure each joist has proper support and bearing, and fit strutting at mid-span on longer spans. As I go I’d check the joists are level and in line, packing where needed, so the floor is flat for the boarding.",
      prompts:["What would the drawings and details tell you?","How would you set out the joists?","What timber and fixings would you use?","How would the joists be supported?","How would you check level and alignment?"]},
    {model:"I’d check the drawings for the size and position of the opening. Before cutting anything I’d look at the existing structure to see which joists or rafters are affected and whether it needs temporary support. I’d set out the opening accurately, marking where to cut and where the trimmers and trimming joists go. Working safely from a proper platform, I’d support the joists, then cut the trimmed joists back. I’d fit the trimmers and double up the trimming joists with the right hangers or joints, then check the opening is square and the right size for the hatch.",
      prompts:["What would you check on the drawings?","What would you look for in the existing structure?","How would you set out the opening?","How would you cut and support it safely?","How would you fit the trimmers and check it?"]},
    {model:"I’d measure the room and plan the sequence, starting from the corners and working around the openings so joints fall in the right places. I’d choose straight timber and the right tools: a mitre saw, a coping saw for scribes and a nail gun or fixings. For corners I’d scribe the internal corners and mitre the external ones so the joints stay tight. I’d fix it securely into studs or plugs with the right length fixings, and glue the mitres. Finally I’d check the alignment, that it’s tight to the wall and floor, fill any nail holes and leave a clean, professional finish.",
      prompts:["How would you measure and plan the sequence?","What timber and tools would you use?","How would you joint the corners?","How would you fix it securely?","How would you check the alignment and finish?"]},
    {model:"I’d check the finished work against the drawings and specification, as an inspection would. I’d take measurements to check the sizes are right and that everything is plumb, level and in alignment. I’d check the joints are tight and the fixings are secure and punched or covered. If I found any defects, like a gap, a split or a proud fixing, I’d put them right or report them to my supervisor. Then I’d do my housekeeping: clear the area, store the tools safely and put waste in the right skip so the area is safe.",
      prompts:["What would you check the work against?","Which measurements and checks would you make?","What would you look for in the joints and fixings?","How would you deal with defects?","What would you do to finish off?"]}
  ],
  benchJoinery:[
    {model:"I’d read the drawing and specification for the sizes, the sections, the joints and the finish. I’d select timber that’s straight, dry and free of defects, and prepare a cutting list. I’d use the machinery safely, with the guards set and the right push sticks, and wear PPE like ear and eye protection and dust masks. I’d set out a rod, mark out the joints, machine and cut them, then dry assemble to check the fit before glueing and cramping it square. Finally I’d check the dimensions against the drawing, clean up the joints and sand it ready for the finish.",
      prompts:["What would the drawing and specification tell you?","How would you select the timber?","How would you use the tools and machinery safely?","How would you make and assemble the joints?","How would you check the dimensions and finish?"]},
    {model:"I’d take the joint dimensions from the drawing: the mortice width, usually a third of the timber thickness, and the tenon length. I’d mark out accurately with a marking gauge, mortice gauge, try square and a sharp pencil or knife, working from the face side and face edge. Using the tools safely, I’d cut the mortice with a chisel or a mortiser, and the tenon with a saw or tenoner, cutting on the waste side of the line. Then I’d dry assemble the joint to check it’s tight, square and flush before glueing it up.",
      prompts:["How would you work out the joint dimensions?","How would you mark it out?","How would you use the tools safely?","How would you cut the mortice and tenon?","How would you check it with a dry assembly?"]},
    {model:"I’d inspect both components to see exactly where they don’t fit, looking for tight spots, gaps or twist. I’d check them against the drawings and the dimensions to see which part is wrong. Then I’d look back at the marking out and machining to find the cause, like a mistake in setting out or a machine that wasn’t set correctly. I’d make a controlled adjustment, taking off a little at a time with a plane or chisel rather than too much at once. Finally I’d test fit it again and check it’s square and flush.",
      prompts:["How would you inspect the components?","What would you check against the drawings?","Where in the marking or machining could it have gone wrong?","How would you adjust it?","How would you check the fit afterwards?"]},
    {model:"I’d inspect the component for defects like machine marks, splits, glue marks or dents. I’d check the dimensions and accuracy against the drawing, and that it’s square. For surface preparation I’d remove glue, fill small defects if allowed, and sand through the grits in the direction of the grain, starting with a coarser paper and finishing fine. I’d check the edges and any profile are crisp and even, softening sharp arrises. Then I’d remove the dust so it’s clean and ready for finishing.",
      prompts:["What defects would you look for?","How would you check dimensions and accuracy?","How would you prepare the surface?","What would you check on the edges and profile?","How would you know it’s ready for finishing?"]},
    {model:"I’d compare the finished job against the drawing and the cutting list. I’d check the dimensions, that it’s square and that the fit of any doors or drawers is even. I’d check the surface finish for scratches, glue or sanding marks. If there are any problems I can’t put right, I’d report the issues to my supervisor and write them down, along with any documentation like the job sheet or quality check sheet. Then I’d do my workshop housekeeping: clean the machines, put the tools away and sweep up, so the workshop is safe.",
      prompts:["What would you compare the job against?","How would you check the dimensions and fit?","What would you check on the surface finish?","How would you report any issues?","What workshop housekeeping would you do?"]}
  ]
};
