/* Evia test banks. Source copied from DDRNFinch/EPA main for offline learner testing.
   Maths and English are here for everyone; each trade's EPA questions and discussions are in its own file
   (test-bank-*.js), loaded with the learner's course pack (packs.js). */
const EPA_DISCUSSIONS={};
const EPA_QUESTIONS={};

const EPA_MATHS_QUESTIONS=[
["Fractions, Decimals and Percentages","A trade merchant prices a pack of timber at £150 before applying a 20% trade discount.",["£110.00","£120.00","£130.00","£140.00"],"£120.00","To find a 20% discount, calculate 20% of £150 (£30) and subtract it from the original total (£150 - £30 = £120).","If an item costs £40 and has a 25% discount (£10 off), what is the final price?",["£30","£35"],"£30"],
["Fractions, Decimals and Percentages","An apprentice completes 18 out of a total target of 24 flooring boards. What percentage of the target has been completed?",["65%","70%","75%","80%"],"75%","Divide the part by the total (18 ÷ 24 = 0.75) and multiply by 100 to get 75%.","If you score 3 out of 4 on a test, what is that as a percentage?",["75%","60%"],"75%"],
["Fractions, Decimals and Percentages","A material budget increases from £500 to £550 over the year. What is the percentage increase in the budget?",["5%","10%","15%","20%"],"10%","Find the increase (£50), divide it by the original amount (£500), and multiply by 100 (50 ÷ 500 = 0.10, or 10%).","If a price goes up by £10 from an original £100, what is the percentage increase?",["10%","5%"],"10%"],
["Ratio, Proportion and Scaling","A mortar mix uses cement and sand in the ratio 1 : 3. If you use 3 bags of cement, how many bags of sand do you need?",["6 bags","8 bags","9 bags","12 bags"],"9 bags","For every 1 part of cement, you need 3 parts of sand. Multiply the cement amount by 3 (3 × 3 = 9).","If the ratio is 1 : 2 and you use 4 bags of cement, how much sand do you need?",["8 bags","6 bags"],"8 bags"],
["Ratio, Proportion and Scaling","If 2 workers can complete a site hoarding installation in 6 days, how many days will it take 4 workers to complete the exact same task working at the same rate?",["2 days","3 days","4 days","12 days"],"3 days","This is inverse proportion. Multiply workers by days to find total worker-days (2 × 6 = 12), then divide by the new worker count (12 ÷ 4 = 3 days).","If 2 workers take 4 days to paint a wall, how many days for 4 workers?",["2 days","4 days"],"2 days"],
["Ratio, Proportion and Scaling","On an architectural scale drawing, a dimension of 20 mm represents an actual length of 1 metre (1,000 mm). What is the scale ratio?",["1 : 20","1 : 50","1 : 100","1 : 200"],"1 : 50","Divide the actual measurement (1,000 mm) by the drawing measurement (20 mm) to find the scale factor (1,000 ÷ 20 = 50), giving a ratio of 1 : 50.","If 10 mm represents 100 mm, what is the scale ratio?",["1 : 10","1 : 20"],"1 : 10"],
["Measures, Shape and Space","What is the area of a rectangular workshop floor measuring 6 metres long by 4 metres wide?",["10 m²","20 m²","24 m²","36 m²"],"24 m²","Area is calculated by multiplying length by width (6 × 4 = 24), not by adding them together.","What is the area of a rug measuring 3 m by 3 m?",["9 m²","6 m²"],"9 m²"],
["Measures, Shape and Space","A room measures 5 m long and 3 m wide. What is the total perimeter of the room?",["8 m","15 m","16 m","25 m"],"16 m","Perimeter is the total distance around the outside. Add all four sides together (5 + 5 + 3 + 3 = 16 m).","What is the perimeter of a square with sides measuring 2 m?",["8 m","6 m"],"8 m"],
["Measures, Shape and Space","What is the volume of a rectangular storage box measuring 2 m long, 1 m wide, and 1.5 m high?",["3.0 m³","4.5 m³","6.0 m³","7.5 m³"],"3.0 m³","Volume is length × width × height (2 × 1 × 1.5 = 3.0 m³).","What is the volume of a box measuring 2 m × 2 m × 2 m?",["8 m³","6 m³"],"8 m³"],
["Handling Data and Statistics","An apprentice records the following daily timber cutting times in minutes: 30, 40, 50, 40, 60. What is the median time?",["35 minutes","40 minutes","45 minutes","50 minutes"],"40 minutes","Put the numbers in order from smallest to largest (30, 40, 40, 50, 60). The middle value is 40.","Find the median of these numbers: 10, 20, 30.",["20","10"],"20"],
["Handling Data and Statistics","A builder records daily delivery delays in minutes over 4 days: 10, 20, 0, 10. What is the mean (average) delay?",["5 minutes","10 minutes","15 minutes","20 minutes"],"10 minutes","Add all values together (10 + 20 + 0 + 10 = 40) and divide by the number of days (4), giving 40 ÷ 4 = 10.","Find the mean of 2, 4, and 6.",["4","6"],"4"],
["Handling Data and Statistics","A set of test scores ranges from a minimum of 45 to a maximum of 85. What is the range of the dataset?",["30","40","45","130"],"40","The range is the highest value minus the lowest value (85 - 45 = 40).","What is the range if the highest score is 50 and the lowest score is 20?",["30","20"],"30"]
];

const EPA_ENGLISH_QUESTIONS=[
["Reading Comprehension, Inference and Analysis","Read this project review excerpt: “Whilst the site supervisor completed the framing phase early, one wonders if electrical snags could have been avoided with better communication.” What is the writer’s attitude?",["Unconditional praise for all management","Balanced, acknowledging speed while questioning communication","Complete dismissal of the construction project","Supportive of electrical teams only"],"Balanced, acknowledging speed while questioning communication","The writer notes a positive (“completed... early”) but also raises a critique (“wondered if... avoided”), showing a balanced viewpoint.","Identify the tone: “The work is neat, but it took twice as long.”",["Balanced / Critical","Unconditionally positive"],"Balanced / Critical"],
["Reading Comprehension, Inference and Analysis","Read this tool advertisement: “Our new drill is simply the most revolutionary, indestructible engineering marvel ever made.” What stylistic feature is used here?",["Objective technical data reporting","Subjective hyperbole and persuasive marketing language","Formal health and safety regulation text","Neutral instructional manual text"],"Subjective hyperbole and persuasive marketing language","Words like “indestructible marvel” are exaggerated claims meant to persuade buyers, which is known as hyperbole.","Is “This hammer is okay” or “This is the greatest hammer in the universe!” an example of advertising hyperbole?",["This is the greatest hammer in the universe!","This hammer is okay"],"This is the greatest hammer in the universe!"],
["Reading Comprehension, Inference and Analysis","When comparing two articles on housing development written by a property developer and a local resident, what core skill is required?",["Memorizing every single word","Identifying differing bias, viewpoints, and motivations","Assuming both authors feel the exact same way","Ignoring the authors’ backgrounds"],"Identifying differing bias, viewpoints, and motivations","Different writers have different personal stakes, so you must look at how their background creates bias or shapes their viewpoint.","Would a business owner and a customer have different views on high prices?",["Yes, their differing perspectives shape their viewpoint.","No, they would always have the same viewpoint."],"Yes, their differing perspectives shape their viewpoint."],
["Writing Composition, Structure and Formal Register","When drafting a formal technical report for college management, which register is appropriate?",["Informal slang and casual abbreviations","Objective, professional tone structured with clear headings","Highly emotional and dramatic storytelling","Text-message shorthand"],"Objective, professional tone structured with clear headings","Formal reports require a professional, objective tone and clear layout, avoiding slang or emotional language.","Choose the more formal sentence: “The tool broke down” or “The equipment experienced a mechanical failure.”",["The equipment experienced a mechanical failure.","The tool broke down"],"The equipment experienced a mechanical failure."],
["Writing Composition, Structure and Formal Register","Which transitional word is best for introducing a contrasting argument in a paragraph?",["Consequently","Furthermore","However","Similarly"],"However","“However” is used specifically to signal a contrast or shift away from a previous point.","To show a contrast between liking tea and disliking coffee, which word fits best: Furthermore or However?",["However","Furthermore"],"However"],
["Writing Composition, Structure and Formal Register","Which sentence uses proper formal vocabulary for an incident report?",["The worker slipped on grease and went flying.","An operative experienced a slip hazard due to uncontained lubricant spillage.","It was really bad when someone fell down today.","Guys on site need to watch out."],"An operative experienced a slip hazard due to uncontained lubricant spillage.","Formal reports require professional terminology like “operative” and “spillage” instead of casual slang like “went flying” or “guys”.","Choose the formal term for “messy”: Untidy hazard or Gross state.",["Untidy hazard","Gross state"],"Untidy hazard"],
["Spelling, Punctuation and Grammar","Choose the sentence that punctuates an embedded relative clause correctly with commas.",["The safety officer who inspected the scaffolding yesterday issued a notice.","The safety officer, who inspected the scaffolding yesterday, issued a notice.","The safety officer who inspected the scaffolding, yesterday issued a notice.","The safety officer, who inspected the scaffolding yesterday issued a notice."],"The safety officer, who inspected the scaffolding yesterday, issued a notice.","Extra descriptive clauses embedded in the middle of a sentence must be wrapped in a pair of commas.","Fix this clause with commas: “My car which is red is fast.”",["My car, which is red, is fast.","My car which is red is fast."],"My car, which is red, is fast."],
["Spelling, Punctuation and Grammar","Which of the following words is spelled correctly?",["Enviroment","Environment","Enviornment","Envrionment"],"Environment","Remember that environment contains a middle “n” right before the “m”.","Choose the correct spelling: necessary or necissary.",["necessary","necissary"],"necessary"],
["Spelling, Punctuation and Grammar","Identify the sentence that keeps consistent verb tense throughout.",["The apprentice measures the timber and then cuts the joint.","The apprentice measured the timber and cuts the joint.","The apprentice measures the timber and cut the joint.","The apprentice measuring the timber and cut the joint."],"The apprentice measures the timber and then cuts the joint.","Both verbs need to match in tense. Option A uses the present tense for both (“measures” and “cuts”).","Fix the tense mismatch: “He walks to work and ran home.”",["He walks to work and runs home.","He walks to work and ran home."],"He walks to work and runs home."]
];
